package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "AREA_DOWN".
 */
public class Area_down {

	private Long id;
	private String areaCode;
	private String areaName;
	private String areaType;
	private String parentAreaCode;
	private String levelOrder;

	// KEEP FIELDS - put your custom fields here
	public Area_down() {
		areaCode = "";
		areaName = "";
		areaType = "";
		parentAreaCode = "";
		levelOrder = "";

	}

	// KEEP FIELDS END

	public Area_down(Long id) {
		this.id = id;
	}

	public Area_down(Long id, String areaCode, String areaName,
			String areaType, String parentAreaCode, String levelOrder) {
		this.id = id;
		this.areaCode = areaCode;
		this.areaName = areaName;
		this.areaType = areaType;
		this.parentAreaCode = parentAreaCode;
		this.levelOrder = levelOrder;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public String getAreaType() {
		return areaType;
	}

	public void setAreaType(String areaType) {
		this.areaType = areaType;
	}

	public String getParentAreaCode() {
		return parentAreaCode;
	}

	public void setParentAreaCode(String parentAreaCode) {
		this.parentAreaCode = parentAreaCode;
	}

	public String getLevelOrder() {
		return levelOrder;
	}

	public void setLevelOrder(String levelOrder) {
		this.levelOrder = levelOrder;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
