package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CHILD_SPECIAL_DOWN".
 */
public class ChildSpecial_down {

	private String personId;
	private String specialNo;
	private String name;
	private String genderCode;
	private String birthday;
	private String householdRegister;
	private String childHealthCardNo;
	private String birthWeight;
	private String birthHeight;
	private String parity;
	private String deliveryTimes;
	private String deliveryGestationalWeeks;
	private String deliveryModeCode;
	private String childbirth;
	private String birthHospital;
	private String fatherName;
	private String matherName;
	private String fatherContac;
	private String matherContac;
	private String UNHSCode;
	private String CYP17Code;
	private String PKUCode;
	private String CHCode;
	private String highRiskCode;
	private String highRiskFactors;
	private String apgar1;
	private String apgar5;
	private String apgar10;
	private String pastHistory;
	private String allergicHistory;
	private String childbirthHospital;
	private String childbirthDoctor;
	private String childbirthAssistant;
	private String registerDate;
	private String registerOrgCode;
	private String registerOrgName;
	private String registerDoctorCode;
	private String registerDoctorName;

	// KEEP FIELDS - put your custom fields here
	public ChildSpecial_down() {
		personId = "";
		specialNo = "";
		name = "";
		genderCode = "";
		birthday = "";
		householdRegister = "";
		childHealthCardNo = "";
		birthWeight = "";
		birthHeight = "";
		parity = "";
		deliveryTimes = "";
		deliveryGestationalWeeks = "";
		deliveryModeCode = "";
		childbirth = "";
		birthHospital = "";
		fatherName = "";
		matherName = "";
		fatherContac = "";
		matherContac = "";
		UNHSCode = "";
		CYP17Code = "";
		PKUCode = "";
		CHCode = "";
		highRiskCode = "";
		highRiskFactors = "";
		apgar1 = "";
		apgar5 = "";
		apgar10 = "";
		pastHistory = "";
		allergicHistory = "";
		childbirthHospital = "";
		childbirthDoctor = "";
		childbirthAssistant = "";
		registerDate = "";
		registerOrgCode = "";
		registerOrgName = "";
		registerDoctorCode = "";
		registerDoctorName = "";

	}

	// KEEP FIELDS END

	public ChildSpecial_down(String personId) {
		this.personId = personId;
	}

	public ChildSpecial_down(String personId, String specialNo, String name,
			String genderCode, String birthday, String householdRegister,
			String childHealthCardNo, String birthWeight, String birthHeight,
			String parity, String deliveryTimes,
			String deliveryGestationalWeeks, String deliveryModeCode,
			String childbirth, String birthHospital, String fatherName,
			String matherName, String fatherContac, String matherContac,
			String UNHSCode, String CYP17Code, String PKUCode, String CHCode,
			String highRiskCode, String highRiskFactors, String apgar1,
			String apgar5, String apgar10, String pastHistory,
			String allergicHistory, String childbirthHospital,
			String childbirthDoctor, String childbirthAssistant,
			String registerDate, String registerOrgCode,
			String registerOrgName, String registerDoctorCode,
			String registerDoctorName) {
		this.personId = personId;
		this.specialNo = specialNo;
		this.name = name;
		this.genderCode = genderCode;
		this.birthday = birthday;
		this.householdRegister = householdRegister;
		this.childHealthCardNo = childHealthCardNo;
		this.birthWeight = birthWeight;
		this.birthHeight = birthHeight;
		this.parity = parity;
		this.deliveryTimes = deliveryTimes;
		this.deliveryGestationalWeeks = deliveryGestationalWeeks;
		this.deliveryModeCode = deliveryModeCode;
		this.childbirth = childbirth;
		this.birthHospital = birthHospital;
		this.fatherName = fatherName;
		this.matherName = matherName;
		this.fatherContac = fatherContac;
		this.matherContac = matherContac;
		this.UNHSCode = UNHSCode;
		this.CYP17Code = CYP17Code;
		this.PKUCode = PKUCode;
		this.CHCode = CHCode;
		this.highRiskCode = highRiskCode;
		this.highRiskFactors = highRiskFactors;
		this.apgar1 = apgar1;
		this.apgar5 = apgar5;
		this.apgar10 = apgar10;
		this.pastHistory = pastHistory;
		this.allergicHistory = allergicHistory;
		this.childbirthHospital = childbirthHospital;
		this.childbirthDoctor = childbirthDoctor;
		this.childbirthAssistant = childbirthAssistant;
		this.registerDate = registerDate;
		this.registerOrgCode = registerOrgCode;
		this.registerOrgName = registerOrgName;
		this.registerDoctorCode = registerDoctorCode;
		this.registerDoctorName = registerDoctorName;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getSpecialNo() {
		return specialNo;
	}

	public void setSpecialNo(String specialNo) {
		this.specialNo = specialNo;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGenderCode() {
		return genderCode;
	}

	public void setGenderCode(String genderCode) {
		this.genderCode = genderCode;
	}

	public String getBirthday() {
		return birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getHouseholdRegister() {
		return householdRegister;
	}

	public void setHouseholdRegister(String householdRegister) {
		this.householdRegister = householdRegister;
	}

	public String getChildHealthCardNo() {
		return childHealthCardNo;
	}

	public void setChildHealthCardNo(String childHealthCardNo) {
		this.childHealthCardNo = childHealthCardNo;
	}

	public String getBirthWeight() {
		return birthWeight;
	}

	public void setBirthWeight(String birthWeight) {
		this.birthWeight = birthWeight;
	}

	public String getBirthHeight() {
		return birthHeight;
	}

	public void setBirthHeight(String birthHeight) {
		this.birthHeight = birthHeight;
	}

	public String getParity() {
		return parity;
	}

	public void setParity(String parity) {
		this.parity = parity;
	}

	public String getDeliveryTimes() {
		return deliveryTimes;
	}

	public void setDeliveryTimes(String deliveryTimes) {
		this.deliveryTimes = deliveryTimes;
	}

	public String getDeliveryGestationalWeeks() {
		return deliveryGestationalWeeks;
	}

	public void setDeliveryGestationalWeeks(String deliveryGestationalWeeks) {
		this.deliveryGestationalWeeks = deliveryGestationalWeeks;
	}

	public String getDeliveryModeCode() {
		return deliveryModeCode;
	}

	public void setDeliveryModeCode(String deliveryModeCode) {
		this.deliveryModeCode = deliveryModeCode;
	}

	public String getChildbirth() {
		return childbirth;
	}

	public void setChildbirth(String childbirth) {
		this.childbirth = childbirth;
	}

	public String getBirthHospital() {
		return birthHospital;
	}

	public void setBirthHospital(String birthHospital) {
		this.birthHospital = birthHospital;
	}

	public String getFatherName() {
		return fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	public String getMatherName() {
		return matherName;
	}

	public void setMatherName(String matherName) {
		this.matherName = matherName;
	}

	public String getFatherContac() {
		return fatherContac;
	}

	public void setFatherContac(String fatherContac) {
		this.fatherContac = fatherContac;
	}

	public String getMatherContac() {
		return matherContac;
	}

	public void setMatherContac(String matherContac) {
		this.matherContac = matherContac;
	}

	public String getUNHSCode() {
		return UNHSCode;
	}

	public void setUNHSCode(String UNHSCode) {
		this.UNHSCode = UNHSCode;
	}

	public String getCYP17Code() {
		return CYP17Code;
	}

	public void setCYP17Code(String CYP17Code) {
		this.CYP17Code = CYP17Code;
	}

	public String getPKUCode() {
		return PKUCode;
	}

	public void setPKUCode(String PKUCode) {
		this.PKUCode = PKUCode;
	}

	public String getCHCode() {
		return CHCode;
	}

	public void setCHCode(String CHCode) {
		this.CHCode = CHCode;
	}

	public String getHighRiskCode() {
		return highRiskCode;
	}

	public void setHighRiskCode(String highRiskCode) {
		this.highRiskCode = highRiskCode;
	}

	public String getHighRiskFactors() {
		return highRiskFactors;
	}

	public void setHighRiskFactors(String highRiskFactors) {
		this.highRiskFactors = highRiskFactors;
	}

	public String getApgar1() {
		return apgar1;
	}

	public void setApgar1(String apgar1) {
		this.apgar1 = apgar1;
	}

	public String getApgar5() {
		return apgar5;
	}

	public void setApgar5(String apgar5) {
		this.apgar5 = apgar5;
	}

	public String getApgar10() {
		return apgar10;
	}

	public void setApgar10(String apgar10) {
		this.apgar10 = apgar10;
	}

	public String getPastHistory() {
		return pastHistory;
	}

	public void setPastHistory(String pastHistory) {
		this.pastHistory = pastHistory;
	}

	public String getAllergicHistory() {
		return allergicHistory;
	}

	public void setAllergicHistory(String allergicHistory) {
		this.allergicHistory = allergicHistory;
	}

	public String getChildbirthHospital() {
		return childbirthHospital;
	}

	public void setChildbirthHospital(String childbirthHospital) {
		this.childbirthHospital = childbirthHospital;
	}

	public String getChildbirthDoctor() {
		return childbirthDoctor;
	}

	public void setChildbirthDoctor(String childbirthDoctor) {
		this.childbirthDoctor = childbirthDoctor;
	}

	public String getChildbirthAssistant() {
		return childbirthAssistant;
	}

	public void setChildbirthAssistant(String childbirthAssistant) {
		this.childbirthAssistant = childbirthAssistant;
	}

	public String getRegisterDate() {
		return registerDate;
	}

	public void setRegisterDate(String registerDate) {
		this.registerDate = registerDate;
	}

	public String getRegisterOrgCode() {
		return registerOrgCode;
	}

	public void setRegisterOrgCode(String registerOrgCode) {
		this.registerOrgCode = registerOrgCode;
	}

	public String getRegisterOrgName() {
		return registerOrgName;
	}

	public void setRegisterOrgName(String registerOrgName) {
		this.registerOrgName = registerOrgName;
	}

	public String getRegisterDoctorCode() {
		return registerDoctorCode;
	}

	public void setRegisterDoctorCode(String registerDoctorCode) {
		this.registerDoctorCode = registerDoctorCode;
	}

	public String getRegisterDoctorName() {
		return registerDoctorName;
	}

	public void setRegisterDoctorName(String registerDoctorName) {
		this.registerDoctorName = registerDoctorName;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
