package com.c102c.app.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.c102c.app.model.DiabetesFlup_upload;
import com.c102c.app.model.HypertensionFlup_upload;
import com.c102c.app.model.HypertensionScreen_upload;
import com.c102c.app.model.NeonatalVisit_upload;
import com.c102c.app.model.Postpartum42Visit_upload;
import com.c102c.app.model.PostpartumVisit_upload;
import com.c102c.app.model.PregnantFirstCheck_upload;
import com.c102c.app.model.PregnantRecheck_upload;
import com.c102c.app.model.Area_down;
import com.c102c.app.model.Org_down;
import com.c102c.app.model.Dictionary_down;
import com.c102c.app.model.User_down;
import com.c102c.app.model.HealthRecord_down;
import com.c102c.app.model.PastHistory_down;
import com.c102c.app.model.HealthRecord_Status;
import com.c102c.app.model.HealthExamination;
import com.c102c.app.model.PregnantSpecial_down;
import com.c102c.app.model.ChildSpecial_down;
import com.c102c.app.model.HypertensionSpecial_down;
import com.c102c.app.model.HypertensionFlup_down;
import com.c102c.app.model.DiabetesSpecial_down;
import com.c102c.app.model.DiabetesFlup_down;
import com.c102c.app.model.Person_down;
import com.c102c.app.model.RequestMessage;
import com.c102c.app.model.LocalMeasurementXueYa;
import com.c102c.app.model.LocalMeasurementEWen;
import com.c102c.app.model.LocalMeasurementXueTang;
import com.c102c.app.model.LocalMeasurementXueYang;
import com.c102c.app.model.LocalMeasurementXinDian;
import com.c102c.app.model.LocalMeasurementNiaoYe;
import com.c102c.app.model.LocalMeasurementBaiXiBao;
import com.c102c.app.model.LocalJieZhen;
import com.c102c.app.model.LocalZhuanZhen;

import com.c102c.app.model.DiabetesFlup_uploadDao;
import com.c102c.app.model.HypertensionFlup_uploadDao;
import com.c102c.app.model.HypertensionScreen_uploadDao;
import com.c102c.app.model.NeonatalVisit_uploadDao;
import com.c102c.app.model.Postpartum42Visit_uploadDao;
import com.c102c.app.model.PostpartumVisit_uploadDao;
import com.c102c.app.model.PregnantFirstCheck_uploadDao;
import com.c102c.app.model.PregnantRecheck_uploadDao;
import com.c102c.app.model.Area_downDao;
import com.c102c.app.model.Org_downDao;
import com.c102c.app.model.Dictionary_downDao;
import com.c102c.app.model.User_downDao;
import com.c102c.app.model.HealthRecord_downDao;
import com.c102c.app.model.PastHistory_downDao;
import com.c102c.app.model.HealthRecord_StatusDao;
import com.c102c.app.model.HealthExaminationDao;
import com.c102c.app.model.PregnantSpecial_downDao;
import com.c102c.app.model.ChildSpecial_downDao;
import com.c102c.app.model.HypertensionSpecial_downDao;
import com.c102c.app.model.HypertensionFlup_downDao;
import com.c102c.app.model.DiabetesSpecial_downDao;
import com.c102c.app.model.DiabetesFlup_downDao;
import com.c102c.app.model.Person_downDao;
import com.c102c.app.model.RequestMessageDao;
import com.c102c.app.model.LocalMeasurementXueYaDao;
import com.c102c.app.model.LocalMeasurementEWenDao;
import com.c102c.app.model.LocalMeasurementXueTangDao;
import com.c102c.app.model.LocalMeasurementXueYangDao;
import com.c102c.app.model.LocalMeasurementXinDianDao;
import com.c102c.app.model.LocalMeasurementNiaoYeDao;
import com.c102c.app.model.LocalMeasurementBaiXiBaoDao;
import com.c102c.app.model.LocalJieZhenDao;
import com.c102c.app.model.LocalZhuanZhenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diabetesFlup_uploadDaoConfig;
    private final DaoConfig hypertensionFlup_uploadDaoConfig;
    private final DaoConfig hypertensionScreen_uploadDaoConfig;
    private final DaoConfig neonatalVisit_uploadDaoConfig;
    private final DaoConfig postpartum42Visit_uploadDaoConfig;
    private final DaoConfig postpartumVisit_uploadDaoConfig;
    private final DaoConfig pregnantFirstCheck_uploadDaoConfig;
    private final DaoConfig pregnantRecheck_uploadDaoConfig;
    private final DaoConfig area_downDaoConfig;
    private final DaoConfig org_downDaoConfig;
    private final DaoConfig dictionary_downDaoConfig;
    private final DaoConfig user_downDaoConfig;
    private final DaoConfig healthRecord_downDaoConfig;
    private final DaoConfig pastHistory_downDaoConfig;
    private final DaoConfig healthRecord_StatusDaoConfig;
    private final DaoConfig healthExaminationDaoConfig;
    private final DaoConfig pregnantSpecial_downDaoConfig;
    private final DaoConfig childSpecial_downDaoConfig;
    private final DaoConfig hypertensionSpecial_downDaoConfig;
    private final DaoConfig hypertensionFlup_downDaoConfig;
    private final DaoConfig diabetesSpecial_downDaoConfig;
    private final DaoConfig diabetesFlup_downDaoConfig;
    private final DaoConfig person_downDaoConfig;
    private final DaoConfig requestMessageDaoConfig;
    private final DaoConfig localMeasurementXueYaDaoConfig;
    private final DaoConfig localMeasurementEWenDaoConfig;
    private final DaoConfig localMeasurementXueTangDaoConfig;
    private final DaoConfig localMeasurementXueYangDaoConfig;
    private final DaoConfig localMeasurementXinDianDaoConfig;
    private final DaoConfig localMeasurementNiaoYeDaoConfig;
    private final DaoConfig localMeasurementBaiXiBaoDaoConfig;
    private final DaoConfig localJieZhenDaoConfig;
    private final DaoConfig localZhuanZhenDaoConfig;

    private final DiabetesFlup_uploadDao diabetesFlup_uploadDao;
    private final HypertensionFlup_uploadDao hypertensionFlup_uploadDao;
    private final HypertensionScreen_uploadDao hypertensionScreen_uploadDao;
    private final NeonatalVisit_uploadDao neonatalVisit_uploadDao;
    private final Postpartum42Visit_uploadDao postpartum42Visit_uploadDao;
    private final PostpartumVisit_uploadDao postpartumVisit_uploadDao;
    private final PregnantFirstCheck_uploadDao pregnantFirstCheck_uploadDao;
    private final PregnantRecheck_uploadDao pregnantRecheck_uploadDao;
    private final Area_downDao area_downDao;
    private final Org_downDao org_downDao;
    private final Dictionary_downDao dictionary_downDao;
    private final User_downDao user_downDao;
    private final HealthRecord_downDao healthRecord_downDao;
    private final PastHistory_downDao pastHistory_downDao;
    private final HealthRecord_StatusDao healthRecord_StatusDao;
    private final HealthExaminationDao healthExaminationDao;
    private final PregnantSpecial_downDao pregnantSpecial_downDao;
    private final ChildSpecial_downDao childSpecial_downDao;
    private final HypertensionSpecial_downDao hypertensionSpecial_downDao;
    private final HypertensionFlup_downDao hypertensionFlup_downDao;
    private final DiabetesSpecial_downDao diabetesSpecial_downDao;
    private final DiabetesFlup_downDao diabetesFlup_downDao;
    private final Person_downDao person_downDao;
    private final RequestMessageDao requestMessageDao;
    private final LocalMeasurementXueYaDao localMeasurementXueYaDao;
    private final LocalMeasurementEWenDao localMeasurementEWenDao;
    private final LocalMeasurementXueTangDao localMeasurementXueTangDao;
    private final LocalMeasurementXueYangDao localMeasurementXueYangDao;
    private final LocalMeasurementXinDianDao localMeasurementXinDianDao;
    private final LocalMeasurementNiaoYeDao localMeasurementNiaoYeDao;
    private final LocalMeasurementBaiXiBaoDao localMeasurementBaiXiBaoDao;
    private final LocalJieZhenDao localJieZhenDao;
    private final LocalZhuanZhenDao localZhuanZhenDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diabetesFlup_uploadDaoConfig = daoConfigMap.get(DiabetesFlup_uploadDao.class).clone();
        diabetesFlup_uploadDaoConfig.initIdentityScope(type);

        hypertensionFlup_uploadDaoConfig = daoConfigMap.get(HypertensionFlup_uploadDao.class).clone();
        hypertensionFlup_uploadDaoConfig.initIdentityScope(type);

        hypertensionScreen_uploadDaoConfig = daoConfigMap.get(HypertensionScreen_uploadDao.class).clone();
        hypertensionScreen_uploadDaoConfig.initIdentityScope(type);

        neonatalVisit_uploadDaoConfig = daoConfigMap.get(NeonatalVisit_uploadDao.class).clone();
        neonatalVisit_uploadDaoConfig.initIdentityScope(type);

        postpartum42Visit_uploadDaoConfig = daoConfigMap.get(Postpartum42Visit_uploadDao.class).clone();
        postpartum42Visit_uploadDaoConfig.initIdentityScope(type);

        postpartumVisit_uploadDaoConfig = daoConfigMap.get(PostpartumVisit_uploadDao.class).clone();
        postpartumVisit_uploadDaoConfig.initIdentityScope(type);

        pregnantFirstCheck_uploadDaoConfig = daoConfigMap.get(PregnantFirstCheck_uploadDao.class).clone();
        pregnantFirstCheck_uploadDaoConfig.initIdentityScope(type);

        pregnantRecheck_uploadDaoConfig = daoConfigMap.get(PregnantRecheck_uploadDao.class).clone();
        pregnantRecheck_uploadDaoConfig.initIdentityScope(type);

        area_downDaoConfig = daoConfigMap.get(Area_downDao.class).clone();
        area_downDaoConfig.initIdentityScope(type);

        org_downDaoConfig = daoConfigMap.get(Org_downDao.class).clone();
        org_downDaoConfig.initIdentityScope(type);

        dictionary_downDaoConfig = daoConfigMap.get(Dictionary_downDao.class).clone();
        dictionary_downDaoConfig.initIdentityScope(type);

        user_downDaoConfig = daoConfigMap.get(User_downDao.class).clone();
        user_downDaoConfig.initIdentityScope(type);

        healthRecord_downDaoConfig = daoConfigMap.get(HealthRecord_downDao.class).clone();
        healthRecord_downDaoConfig.initIdentityScope(type);

        pastHistory_downDaoConfig = daoConfigMap.get(PastHistory_downDao.class).clone();
        pastHistory_downDaoConfig.initIdentityScope(type);

        healthRecord_StatusDaoConfig = daoConfigMap.get(HealthRecord_StatusDao.class).clone();
        healthRecord_StatusDaoConfig.initIdentityScope(type);

        healthExaminationDaoConfig = daoConfigMap.get(HealthExaminationDao.class).clone();
        healthExaminationDaoConfig.initIdentityScope(type);

        pregnantSpecial_downDaoConfig = daoConfigMap.get(PregnantSpecial_downDao.class).clone();
        pregnantSpecial_downDaoConfig.initIdentityScope(type);

        childSpecial_downDaoConfig = daoConfigMap.get(ChildSpecial_downDao.class).clone();
        childSpecial_downDaoConfig.initIdentityScope(type);

        hypertensionSpecial_downDaoConfig = daoConfigMap.get(HypertensionSpecial_downDao.class).clone();
        hypertensionSpecial_downDaoConfig.initIdentityScope(type);

        hypertensionFlup_downDaoConfig = daoConfigMap.get(HypertensionFlup_downDao.class).clone();
        hypertensionFlup_downDaoConfig.initIdentityScope(type);

        diabetesSpecial_downDaoConfig = daoConfigMap.get(DiabetesSpecial_downDao.class).clone();
        diabetesSpecial_downDaoConfig.initIdentityScope(type);

        diabetesFlup_downDaoConfig = daoConfigMap.get(DiabetesFlup_downDao.class).clone();
        diabetesFlup_downDaoConfig.initIdentityScope(type);

        person_downDaoConfig = daoConfigMap.get(Person_downDao.class).clone();
        person_downDaoConfig.initIdentityScope(type);

        requestMessageDaoConfig = daoConfigMap.get(RequestMessageDao.class).clone();
        requestMessageDaoConfig.initIdentityScope(type);

        localMeasurementXueYaDaoConfig = daoConfigMap.get(LocalMeasurementXueYaDao.class).clone();
        localMeasurementXueYaDaoConfig.initIdentityScope(type);

        localMeasurementEWenDaoConfig = daoConfigMap.get(LocalMeasurementEWenDao.class).clone();
        localMeasurementEWenDaoConfig.initIdentityScope(type);

        localMeasurementXueTangDaoConfig = daoConfigMap.get(LocalMeasurementXueTangDao.class).clone();
        localMeasurementXueTangDaoConfig.initIdentityScope(type);

        localMeasurementXueYangDaoConfig = daoConfigMap.get(LocalMeasurementXueYangDao.class).clone();
        localMeasurementXueYangDaoConfig.initIdentityScope(type);

        localMeasurementXinDianDaoConfig = daoConfigMap.get(LocalMeasurementXinDianDao.class).clone();
        localMeasurementXinDianDaoConfig.initIdentityScope(type);

        localMeasurementNiaoYeDaoConfig = daoConfigMap.get(LocalMeasurementNiaoYeDao.class).clone();
        localMeasurementNiaoYeDaoConfig.initIdentityScope(type);

        localMeasurementBaiXiBaoDaoConfig = daoConfigMap.get(LocalMeasurementBaiXiBaoDao.class).clone();
        localMeasurementBaiXiBaoDaoConfig.initIdentityScope(type);

        localJieZhenDaoConfig = daoConfigMap.get(LocalJieZhenDao.class).clone();
        localJieZhenDaoConfig.initIdentityScope(type);

        localZhuanZhenDaoConfig = daoConfigMap.get(LocalZhuanZhenDao.class).clone();
        localZhuanZhenDaoConfig.initIdentityScope(type);

        diabetesFlup_uploadDao = new DiabetesFlup_uploadDao(diabetesFlup_uploadDaoConfig, this);
        hypertensionFlup_uploadDao = new HypertensionFlup_uploadDao(hypertensionFlup_uploadDaoConfig, this);
        hypertensionScreen_uploadDao = new HypertensionScreen_uploadDao(hypertensionScreen_uploadDaoConfig, this);
        neonatalVisit_uploadDao = new NeonatalVisit_uploadDao(neonatalVisit_uploadDaoConfig, this);
        postpartum42Visit_uploadDao = new Postpartum42Visit_uploadDao(postpartum42Visit_uploadDaoConfig, this);
        postpartumVisit_uploadDao = new PostpartumVisit_uploadDao(postpartumVisit_uploadDaoConfig, this);
        pregnantFirstCheck_uploadDao = new PregnantFirstCheck_uploadDao(pregnantFirstCheck_uploadDaoConfig, this);
        pregnantRecheck_uploadDao = new PregnantRecheck_uploadDao(pregnantRecheck_uploadDaoConfig, this);
        area_downDao = new Area_downDao(area_downDaoConfig, this);
        org_downDao = new Org_downDao(org_downDaoConfig, this);
        dictionary_downDao = new Dictionary_downDao(dictionary_downDaoConfig, this);
        user_downDao = new User_downDao(user_downDaoConfig, this);
        healthRecord_downDao = new HealthRecord_downDao(healthRecord_downDaoConfig, this);
        pastHistory_downDao = new PastHistory_downDao(pastHistory_downDaoConfig, this);
        healthRecord_StatusDao = new HealthRecord_StatusDao(healthRecord_StatusDaoConfig, this);
        healthExaminationDao = new HealthExaminationDao(healthExaminationDaoConfig, this);
        pregnantSpecial_downDao = new PregnantSpecial_downDao(pregnantSpecial_downDaoConfig, this);
        childSpecial_downDao = new ChildSpecial_downDao(childSpecial_downDaoConfig, this);
        hypertensionSpecial_downDao = new HypertensionSpecial_downDao(hypertensionSpecial_downDaoConfig, this);
        hypertensionFlup_downDao = new HypertensionFlup_downDao(hypertensionFlup_downDaoConfig, this);
        diabetesSpecial_downDao = new DiabetesSpecial_downDao(diabetesSpecial_downDaoConfig, this);
        diabetesFlup_downDao = new DiabetesFlup_downDao(diabetesFlup_downDaoConfig, this);
        person_downDao = new Person_downDao(person_downDaoConfig, this);
        requestMessageDao = new RequestMessageDao(requestMessageDaoConfig, this);
        localMeasurementXueYaDao = new LocalMeasurementXueYaDao(localMeasurementXueYaDaoConfig, this);
        localMeasurementEWenDao = new LocalMeasurementEWenDao(localMeasurementEWenDaoConfig, this);
        localMeasurementXueTangDao = new LocalMeasurementXueTangDao(localMeasurementXueTangDaoConfig, this);
        localMeasurementXueYangDao = new LocalMeasurementXueYangDao(localMeasurementXueYangDaoConfig, this);
        localMeasurementXinDianDao = new LocalMeasurementXinDianDao(localMeasurementXinDianDaoConfig, this);
        localMeasurementNiaoYeDao = new LocalMeasurementNiaoYeDao(localMeasurementNiaoYeDaoConfig, this);
        localMeasurementBaiXiBaoDao = new LocalMeasurementBaiXiBaoDao(localMeasurementBaiXiBaoDaoConfig, this);
        localJieZhenDao = new LocalJieZhenDao(localJieZhenDaoConfig, this);
        localZhuanZhenDao = new LocalZhuanZhenDao(localZhuanZhenDaoConfig, this);

        registerDao(DiabetesFlup_upload.class, diabetesFlup_uploadDao);
        registerDao(HypertensionFlup_upload.class, hypertensionFlup_uploadDao);
        registerDao(HypertensionScreen_upload.class, hypertensionScreen_uploadDao);
        registerDao(NeonatalVisit_upload.class, neonatalVisit_uploadDao);
        registerDao(Postpartum42Visit_upload.class, postpartum42Visit_uploadDao);
        registerDao(PostpartumVisit_upload.class, postpartumVisit_uploadDao);
        registerDao(PregnantFirstCheck_upload.class, pregnantFirstCheck_uploadDao);
        registerDao(PregnantRecheck_upload.class, pregnantRecheck_uploadDao);
        registerDao(Area_down.class, area_downDao);
        registerDao(Org_down.class, org_downDao);
        registerDao(Dictionary_down.class, dictionary_downDao);
        registerDao(User_down.class, user_downDao);
        registerDao(HealthRecord_down.class, healthRecord_downDao);
        registerDao(PastHistory_down.class, pastHistory_downDao);
        registerDao(HealthRecord_Status.class, healthRecord_StatusDao);
        registerDao(HealthExamination.class, healthExaminationDao);
        registerDao(PregnantSpecial_down.class, pregnantSpecial_downDao);
        registerDao(ChildSpecial_down.class, childSpecial_downDao);
        registerDao(HypertensionSpecial_down.class, hypertensionSpecial_downDao);
        registerDao(HypertensionFlup_down.class, hypertensionFlup_downDao);
        registerDao(DiabetesSpecial_down.class, diabetesSpecial_downDao);
        registerDao(DiabetesFlup_down.class, diabetesFlup_downDao);
        registerDao(Person_down.class, person_downDao);
        registerDao(RequestMessage.class, requestMessageDao);
        registerDao(LocalMeasurementXueYa.class, localMeasurementXueYaDao);
        registerDao(LocalMeasurementEWen.class, localMeasurementEWenDao);
        registerDao(LocalMeasurementXueTang.class, localMeasurementXueTangDao);
        registerDao(LocalMeasurementXueYang.class, localMeasurementXueYangDao);
        registerDao(LocalMeasurementXinDian.class, localMeasurementXinDianDao);
        registerDao(LocalMeasurementNiaoYe.class, localMeasurementNiaoYeDao);
        registerDao(LocalMeasurementBaiXiBao.class, localMeasurementBaiXiBaoDao);
        registerDao(LocalJieZhen.class, localJieZhenDao);
        registerDao(LocalZhuanZhen.class, localZhuanZhenDao);
    }
    
    public void clear() {
        diabetesFlup_uploadDaoConfig.getIdentityScope().clear();
        hypertensionFlup_uploadDaoConfig.getIdentityScope().clear();
        hypertensionScreen_uploadDaoConfig.getIdentityScope().clear();
        neonatalVisit_uploadDaoConfig.getIdentityScope().clear();
        postpartum42Visit_uploadDaoConfig.getIdentityScope().clear();
        postpartumVisit_uploadDaoConfig.getIdentityScope().clear();
        pregnantFirstCheck_uploadDaoConfig.getIdentityScope().clear();
        pregnantRecheck_uploadDaoConfig.getIdentityScope().clear();
        area_downDaoConfig.getIdentityScope().clear();
        org_downDaoConfig.getIdentityScope().clear();
        dictionary_downDaoConfig.getIdentityScope().clear();
        user_downDaoConfig.getIdentityScope().clear();
        healthRecord_downDaoConfig.getIdentityScope().clear();
        pastHistory_downDaoConfig.getIdentityScope().clear();
        healthRecord_StatusDaoConfig.getIdentityScope().clear();
        healthExaminationDaoConfig.getIdentityScope().clear();
        pregnantSpecial_downDaoConfig.getIdentityScope().clear();
        childSpecial_downDaoConfig.getIdentityScope().clear();
        hypertensionSpecial_downDaoConfig.getIdentityScope().clear();
        hypertensionFlup_downDaoConfig.getIdentityScope().clear();
        diabetesSpecial_downDaoConfig.getIdentityScope().clear();
        diabetesFlup_downDaoConfig.getIdentityScope().clear();
        person_downDaoConfig.getIdentityScope().clear();
        requestMessageDaoConfig.getIdentityScope().clear();
        localMeasurementXueYaDaoConfig.getIdentityScope().clear();
        localMeasurementEWenDaoConfig.getIdentityScope().clear();
        localMeasurementXueTangDaoConfig.getIdentityScope().clear();
        localMeasurementXueYangDaoConfig.getIdentityScope().clear();
        localMeasurementXinDianDaoConfig.getIdentityScope().clear();
        localMeasurementNiaoYeDaoConfig.getIdentityScope().clear();
        localMeasurementBaiXiBaoDaoConfig.getIdentityScope().clear();
        localJieZhenDaoConfig.getIdentityScope().clear();
        localZhuanZhenDaoConfig.getIdentityScope().clear();
    }

    public DiabetesFlup_uploadDao getDiabetesFlup_uploadDao() {
        return diabetesFlup_uploadDao;
    }

    public HypertensionFlup_uploadDao getHypertensionFlup_uploadDao() {
        return hypertensionFlup_uploadDao;
    }

    public HypertensionScreen_uploadDao getHypertensionScreen_uploadDao() {
        return hypertensionScreen_uploadDao;
    }

    public NeonatalVisit_uploadDao getNeonatalVisit_uploadDao() {
        return neonatalVisit_uploadDao;
    }

    public Postpartum42Visit_uploadDao getPostpartum42Visit_uploadDao() {
        return postpartum42Visit_uploadDao;
    }

    public PostpartumVisit_uploadDao getPostpartumVisit_uploadDao() {
        return postpartumVisit_uploadDao;
    }

    public PregnantFirstCheck_uploadDao getPregnantFirstCheck_uploadDao() {
        return pregnantFirstCheck_uploadDao;
    }

    public PregnantRecheck_uploadDao getPregnantRecheck_uploadDao() {
        return pregnantRecheck_uploadDao;
    }

    public Area_downDao getArea_downDao() {
        return area_downDao;
    }

    public Org_downDao getOrg_downDao() {
        return org_downDao;
    }

    public Dictionary_downDao getDictionary_downDao() {
        return dictionary_downDao;
    }

    public User_downDao getUser_downDao() {
        return user_downDao;
    }

    public HealthRecord_downDao getHealthRecord_downDao() {
        return healthRecord_downDao;
    }

    public PastHistory_downDao getPastHistory_downDao() {
        return pastHistory_downDao;
    }

    public HealthRecord_StatusDao getHealthRecord_StatusDao() {
        return healthRecord_StatusDao;
    }

    public HealthExaminationDao getHealthExaminationDao() {
        return healthExaminationDao;
    }

    public PregnantSpecial_downDao getPregnantSpecial_downDao() {
        return pregnantSpecial_downDao;
    }

    public ChildSpecial_downDao getChildSpecial_downDao() {
        return childSpecial_downDao;
    }

    public HypertensionSpecial_downDao getHypertensionSpecial_downDao() {
        return hypertensionSpecial_downDao;
    }

    public HypertensionFlup_downDao getHypertensionFlup_downDao() {
        return hypertensionFlup_downDao;
    }

    public DiabetesSpecial_downDao getDiabetesSpecial_downDao() {
        return diabetesSpecial_downDao;
    }

    public DiabetesFlup_downDao getDiabetesFlup_downDao() {
        return diabetesFlup_downDao;
    }

    public Person_downDao getPerson_downDao() {
        return person_downDao;
    }

    public RequestMessageDao getRequestMessageDao() {
        return requestMessageDao;
    }

    public LocalMeasurementXueYaDao getLocalMeasurementXueYaDao() {
        return localMeasurementXueYaDao;
    }

    public LocalMeasurementEWenDao getLocalMeasurementEWenDao() {
        return localMeasurementEWenDao;
    }

    public LocalMeasurementXueTangDao getLocalMeasurementXueTangDao() {
        return localMeasurementXueTangDao;
    }

    public LocalMeasurementXueYangDao getLocalMeasurementXueYangDao() {
        return localMeasurementXueYangDao;
    }

    public LocalMeasurementXinDianDao getLocalMeasurementXinDianDao() {
        return localMeasurementXinDianDao;
    }

    public LocalMeasurementNiaoYeDao getLocalMeasurementNiaoYeDao() {
        return localMeasurementNiaoYeDao;
    }

    public LocalMeasurementBaiXiBaoDao getLocalMeasurementBaiXiBaoDao() {
        return localMeasurementBaiXiBaoDao;
    }

    public LocalJieZhenDao getLocalJieZhenDao() {
        return localJieZhenDao;
    }

    public LocalZhuanZhenDao getLocalZhuanZhenDao() {
        return localZhuanZhenDao;
    }

}
