package com.c102c.app.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.c102c.app.model.DiabetesFlup_down;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DIABETES_FLUP_DOWN".
*/
public class DiabetesFlup_downDao extends AbstractDao<DiabetesFlup_down, String> {

    public static final String TABLENAME = "DIABETES_FLUP_DOWN";

    /**
     * Properties of entity DiabetesFlup_down.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property BusinessKey = new Property(0, String.class, "businessKey", true, "BUSINESS_KEY");
        public final static Property BmiTarget = new Property(1, String.class, "bmiTarget", false, "BMI_TARGET");
        public final static Property PersonId = new Property(2, String.class, "personId", false, "PERSON_ID");
        public final static Property HealthFileNumber = new Property(3, String.class, "healthFileNumber", false, "HEALTH_FILE_NUMBER");
        public final static Property BloodPressureLevel = new Property(4, String.class, "bloodPressureLevel", false, "BLOOD_PRESSURE_LEVEL");
        public final static Property Name = new Property(5, String.class, "name", false, "NAME");
        public final static Property FlupDate = new Property(6, String.class, "flupDate", false, "FLUP_DATE");
        public final static Property FlupMode = new Property(7, String.class, "flupMode", false, "FLUP_MODE");
        public final static Property SymptomCodes = new Property(8, String.class, "symptomCodes", false, "SYMPTOM_CODES");
        public final static Property SpecialNo = new Property(9, String.class, "specialNo", false, "SPECIAL_NO");
        public final static Property SymptomOther = new Property(10, String.class, "symptomOther", false, "SYMPTOM_OTHER");
        public final static Property SBP = new Property(11, String.class, "SBP", false, "SBP");
        public final static Property DBP = new Property(12, String.class, "DBP", false, "DBP");
        public final static Property Weight = new Property(13, String.class, "weight", false, "WEIGHT");
        public final static Property WeightTarget = new Property(14, String.class, "weightTarget", false, "WEIGHT_TARGET");
        public final static Property Bmi = new Property(15, String.class, "bmi", false, "BMI");
        public final static Property DorsalisPedisPulseCode = new Property(16, String.class, "dorsalisPedisPulseCode", false, "DORSALIS_PEDIS_PULSE_CODE");
        public final static Property SignsOther = new Property(17, String.class, "signsOther", false, "SIGNS_OTHER");
        public final static Property DailySmoking = new Property(18, String.class, "dailySmoking", false, "DAILY_SMOKING");
        public final static Property DailySmokingTarget = new Property(19, String.class, "dailySmokingTarget", false, "DAILY_SMOKING_TARGET");
        public final static Property DailyDrinking = new Property(20, String.class, "dailyDrinking", false, "DAILY_DRINKING");
        public final static Property DailyDrinkingTarget = new Property(21, String.class, "dailyDrinkingTarget", false, "DAILY_DRINKING_TARGET");
        public final static Property PerWeekMovements = new Property(22, String.class, "perWeekMovements", false, "PER_WEEK_MOVEMENTS");
        public final static Property PerWeekMovementsTarget = new Property(23, String.class, "perWeekMovementsTarget", false, "PER_WEEK_MOVEMENTS_TARGET");
        public final static Property PerWeekTimes = new Property(24, String.class, "perWeekTimes", false, "PER_WEEK_TIMES");
        public final static Property PerWeekTimesTarget = new Property(25, String.class, "perWeekTimesTarget", false, "PER_WEEK_TIMES_TARGET");
        public final static Property StapleFood = new Property(26, String.class, "stapleFood", false, "STAPLE_FOOD");
        public final static Property StapleFoodTarget = new Property(27, String.class, "stapleFoodTarget", false, "STAPLE_FOOD_TARGET");
        public final static Property PsychologicalCode = new Property(28, String.class, "psychologicalCode", false, "PSYCHOLOGICAL_CODE");
        public final static Property ComplianceCode = new Property(29, String.class, "complianceCode", false, "COMPLIANCE_CODE");
        public final static Property FastingBloodGlucose = new Property(30, String.class, "fastingBloodGlucose", false, "FASTING_BLOOD_GLUCOSE");
        public final static Property HbA1c = new Property(31, String.class, "HbA1c", false, "HB_A1C");
        public final static Property AidCheckDate = new Property(32, String.class, "aidCheckDate", false, "AID_CHECK_DATE");
        public final static Property AidCheck = new Property(33, String.class, "aidCheck", false, "AID_CHECK");
        public final static Property DoseCode = new Property(34, String.class, "doseCode", false, "DOSE_CODE");
        public final static Property AdverseReactionCode = new Property(35, String.class, "adverseReactionCode", false, "ADVERSE_REACTION_CODE");
        public final static Property LowBloodSugarCode = new Property(36, String.class, "lowBloodSugarCode", false, "LOW_BLOOD_SUGAR_CODE");
        public final static Property FlupTypeCode = new Property(37, String.class, "flupTypeCode", false, "FLUP_TYPE_CODE");
        public final static Property MedicationList = new Property(38, String.class, "medicationList", false, "MEDICATION_LIST");
        public final static Property InsulinMedicationType = new Property(39, String.class, "insulinMedicationType", false, "INSULIN_MEDICATION_TYPE");
        public final static Property InsulinMedicationRate = new Property(40, String.class, "insulinMedicationRate", false, "INSULIN_MEDICATION_RATE");
        public final static Property InsulinMedicationDose = new Property(41, String.class, "insulinMedicationDose", false, "INSULIN_MEDICATION_DOSE");
        public final static Property ReferralReason = new Property(42, String.class, "referralReason", false, "REFERRAL_REASON");
        public final static Property ReferralOrg = new Property(43, String.class, "referralOrg", false, "REFERRAL_ORG");
        public final static Property ReferralDepartment = new Property(44, String.class, "referralDepartment", false, "REFERRAL_DEPARTMENT");
        public final static Property FlupDoctorCode = new Property(45, String.class, "flupDoctorCode", false, "FLUP_DOCTOR_CODE");
        public final static Property FlupDoctorName = new Property(46, String.class, "flupDoctorName", false, "FLUP_DOCTOR_NAME");
        public final static Property FlupOrgCode = new Property(47, String.class, "flupOrgCode", false, "FLUP_ORG_CODE");
        public final static Property FlupOrgName = new Property(48, String.class, "flupOrgName", false, "FLUP_ORG_NAME");
        public final static Property NextFlupDate = new Property(49, String.class, "nextFlupDate", false, "NEXT_FLUP_DATE");
    };


    public DiabetesFlup_downDao(DaoConfig config) {
        super(config);
    }
    
    public DiabetesFlup_downDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DIABETES_FLUP_DOWN\" (" + //
                "\"BUSINESS_KEY\" TEXT PRIMARY KEY NOT NULL ," + // 0: businessKey
                "\"BMI_TARGET\" TEXT," + // 1: bmiTarget
                "\"PERSON_ID\" TEXT," + // 2: personId
                "\"HEALTH_FILE_NUMBER\" TEXT," + // 3: healthFileNumber
                "\"BLOOD_PRESSURE_LEVEL\" TEXT," + // 4: bloodPressureLevel
                "\"NAME\" TEXT," + // 5: name
                "\"FLUP_DATE\" TEXT," + // 6: flupDate
                "\"FLUP_MODE\" TEXT," + // 7: flupMode
                "\"SYMPTOM_CODES\" TEXT," + // 8: symptomCodes
                "\"SPECIAL_NO\" TEXT," + // 9: specialNo
                "\"SYMPTOM_OTHER\" TEXT," + // 10: symptomOther
                "\"SBP\" TEXT," + // 11: SBP
                "\"DBP\" TEXT," + // 12: DBP
                "\"WEIGHT\" TEXT," + // 13: weight
                "\"WEIGHT_TARGET\" TEXT," + // 14: weightTarget
                "\"BMI\" TEXT," + // 15: bmi
                "\"DORSALIS_PEDIS_PULSE_CODE\" TEXT," + // 16: dorsalisPedisPulseCode
                "\"SIGNS_OTHER\" TEXT," + // 17: signsOther
                "\"DAILY_SMOKING\" TEXT," + // 18: dailySmoking
                "\"DAILY_SMOKING_TARGET\" TEXT," + // 19: dailySmokingTarget
                "\"DAILY_DRINKING\" TEXT," + // 20: dailyDrinking
                "\"DAILY_DRINKING_TARGET\" TEXT," + // 21: dailyDrinkingTarget
                "\"PER_WEEK_MOVEMENTS\" TEXT," + // 22: perWeekMovements
                "\"PER_WEEK_MOVEMENTS_TARGET\" TEXT," + // 23: perWeekMovementsTarget
                "\"PER_WEEK_TIMES\" TEXT," + // 24: perWeekTimes
                "\"PER_WEEK_TIMES_TARGET\" TEXT," + // 25: perWeekTimesTarget
                "\"STAPLE_FOOD\" TEXT," + // 26: stapleFood
                "\"STAPLE_FOOD_TARGET\" TEXT," + // 27: stapleFoodTarget
                "\"PSYCHOLOGICAL_CODE\" TEXT," + // 28: psychologicalCode
                "\"COMPLIANCE_CODE\" TEXT," + // 29: complianceCode
                "\"FASTING_BLOOD_GLUCOSE\" TEXT," + // 30: fastingBloodGlucose
                "\"HB_A1C\" TEXT," + // 31: HbA1c
                "\"AID_CHECK_DATE\" TEXT," + // 32: aidCheckDate
                "\"AID_CHECK\" TEXT," + // 33: aidCheck
                "\"DOSE_CODE\" TEXT," + // 34: doseCode
                "\"ADVERSE_REACTION_CODE\" TEXT," + // 35: adverseReactionCode
                "\"LOW_BLOOD_SUGAR_CODE\" TEXT," + // 36: lowBloodSugarCode
                "\"FLUP_TYPE_CODE\" TEXT," + // 37: flupTypeCode
                "\"MEDICATION_LIST\" TEXT," + // 38: medicationList
                "\"INSULIN_MEDICATION_TYPE\" TEXT," + // 39: insulinMedicationType
                "\"INSULIN_MEDICATION_RATE\" TEXT," + // 40: insulinMedicationRate
                "\"INSULIN_MEDICATION_DOSE\" TEXT," + // 41: insulinMedicationDose
                "\"REFERRAL_REASON\" TEXT," + // 42: referralReason
                "\"REFERRAL_ORG\" TEXT," + // 43: referralOrg
                "\"REFERRAL_DEPARTMENT\" TEXT," + // 44: referralDepartment
                "\"FLUP_DOCTOR_CODE\" TEXT," + // 45: flupDoctorCode
                "\"FLUP_DOCTOR_NAME\" TEXT," + // 46: flupDoctorName
                "\"FLUP_ORG_CODE\" TEXT," + // 47: flupOrgCode
                "\"FLUP_ORG_NAME\" TEXT," + // 48: flupOrgName
                "\"NEXT_FLUP_DATE\" TEXT);"); // 49: nextFlupDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DIABETES_FLUP_DOWN\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DiabetesFlup_down entity) {
        stmt.clearBindings();
 
        String businessKey = entity.getBusinessKey();
        if (businessKey != null) {
            stmt.bindString(1, businessKey);
        }
 
        String bmiTarget = entity.getBmiTarget();
        if (bmiTarget != null) {
            stmt.bindString(2, bmiTarget);
        }
 
        String personId = entity.getPersonId();
        if (personId != null) {
            stmt.bindString(3, personId);
        }
 
        String healthFileNumber = entity.getHealthFileNumber();
        if (healthFileNumber != null) {
            stmt.bindString(4, healthFileNumber);
        }
 
        String bloodPressureLevel = entity.getBloodPressureLevel();
        if (bloodPressureLevel != null) {
            stmt.bindString(5, bloodPressureLevel);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(6, name);
        }
 
        String flupDate = entity.getFlupDate();
        if (flupDate != null) {
            stmt.bindString(7, flupDate);
        }
 
        String flupMode = entity.getFlupMode();
        if (flupMode != null) {
            stmt.bindString(8, flupMode);
        }
 
        String symptomCodes = entity.getSymptomCodes();
        if (symptomCodes != null) {
            stmt.bindString(9, symptomCodes);
        }
 
        String specialNo = entity.getSpecialNo();
        if (specialNo != null) {
            stmt.bindString(10, specialNo);
        }
 
        String symptomOther = entity.getSymptomOther();
        if (symptomOther != null) {
            stmt.bindString(11, symptomOther);
        }
 
        String SBP = entity.getSBP();
        if (SBP != null) {
            stmt.bindString(12, SBP);
        }
 
        String DBP = entity.getDBP();
        if (DBP != null) {
            stmt.bindString(13, DBP);
        }
 
        String weight = entity.getWeight();
        if (weight != null) {
            stmt.bindString(14, weight);
        }
 
        String weightTarget = entity.getWeightTarget();
        if (weightTarget != null) {
            stmt.bindString(15, weightTarget);
        }
 
        String bmi = entity.getBmi();
        if (bmi != null) {
            stmt.bindString(16, bmi);
        }
 
        String dorsalisPedisPulseCode = entity.getDorsalisPedisPulseCode();
        if (dorsalisPedisPulseCode != null) {
            stmt.bindString(17, dorsalisPedisPulseCode);
        }
 
        String signsOther = entity.getSignsOther();
        if (signsOther != null) {
            stmt.bindString(18, signsOther);
        }
 
        String dailySmoking = entity.getDailySmoking();
        if (dailySmoking != null) {
            stmt.bindString(19, dailySmoking);
        }
 
        String dailySmokingTarget = entity.getDailySmokingTarget();
        if (dailySmokingTarget != null) {
            stmt.bindString(20, dailySmokingTarget);
        }
 
        String dailyDrinking = entity.getDailyDrinking();
        if (dailyDrinking != null) {
            stmt.bindString(21, dailyDrinking);
        }
 
        String dailyDrinkingTarget = entity.getDailyDrinkingTarget();
        if (dailyDrinkingTarget != null) {
            stmt.bindString(22, dailyDrinkingTarget);
        }
 
        String perWeekMovements = entity.getPerWeekMovements();
        if (perWeekMovements != null) {
            stmt.bindString(23, perWeekMovements);
        }
 
        String perWeekMovementsTarget = entity.getPerWeekMovementsTarget();
        if (perWeekMovementsTarget != null) {
            stmt.bindString(24, perWeekMovementsTarget);
        }
 
        String perWeekTimes = entity.getPerWeekTimes();
        if (perWeekTimes != null) {
            stmt.bindString(25, perWeekTimes);
        }
 
        String perWeekTimesTarget = entity.getPerWeekTimesTarget();
        if (perWeekTimesTarget != null) {
            stmt.bindString(26, perWeekTimesTarget);
        }
 
        String stapleFood = entity.getStapleFood();
        if (stapleFood != null) {
            stmt.bindString(27, stapleFood);
        }
 
        String stapleFoodTarget = entity.getStapleFoodTarget();
        if (stapleFoodTarget != null) {
            stmt.bindString(28, stapleFoodTarget);
        }
 
        String psychologicalCode = entity.getPsychologicalCode();
        if (psychologicalCode != null) {
            stmt.bindString(29, psychologicalCode);
        }
 
        String complianceCode = entity.getComplianceCode();
        if (complianceCode != null) {
            stmt.bindString(30, complianceCode);
        }
 
        String fastingBloodGlucose = entity.getFastingBloodGlucose();
        if (fastingBloodGlucose != null) {
            stmt.bindString(31, fastingBloodGlucose);
        }
 
        String HbA1c = entity.getHbA1c();
        if (HbA1c != null) {
            stmt.bindString(32, HbA1c);
        }
 
        String aidCheckDate = entity.getAidCheckDate();
        if (aidCheckDate != null) {
            stmt.bindString(33, aidCheckDate);
        }
 
        String aidCheck = entity.getAidCheck();
        if (aidCheck != null) {
            stmt.bindString(34, aidCheck);
        }
 
        String doseCode = entity.getDoseCode();
        if (doseCode != null) {
            stmt.bindString(35, doseCode);
        }
 
        String adverseReactionCode = entity.getAdverseReactionCode();
        if (adverseReactionCode != null) {
            stmt.bindString(36, adverseReactionCode);
        }
 
        String lowBloodSugarCode = entity.getLowBloodSugarCode();
        if (lowBloodSugarCode != null) {
            stmt.bindString(37, lowBloodSugarCode);
        }
 
        String flupTypeCode = entity.getFlupTypeCode();
        if (flupTypeCode != null) {
            stmt.bindString(38, flupTypeCode);
        }
 
        String medicationList = entity.getMedicationList();
        if (medicationList != null) {
            stmt.bindString(39, medicationList);
        }
 
        String insulinMedicationType = entity.getInsulinMedicationType();
        if (insulinMedicationType != null) {
            stmt.bindString(40, insulinMedicationType);
        }
 
        String insulinMedicationRate = entity.getInsulinMedicationRate();
        if (insulinMedicationRate != null) {
            stmt.bindString(41, insulinMedicationRate);
        }
 
        String insulinMedicationDose = entity.getInsulinMedicationDose();
        if (insulinMedicationDose != null) {
            stmt.bindString(42, insulinMedicationDose);
        }
 
        String referralReason = entity.getReferralReason();
        if (referralReason != null) {
            stmt.bindString(43, referralReason);
        }
 
        String referralOrg = entity.getReferralOrg();
        if (referralOrg != null) {
            stmt.bindString(44, referralOrg);
        }
 
        String referralDepartment = entity.getReferralDepartment();
        if (referralDepartment != null) {
            stmt.bindString(45, referralDepartment);
        }
 
        String flupDoctorCode = entity.getFlupDoctorCode();
        if (flupDoctorCode != null) {
            stmt.bindString(46, flupDoctorCode);
        }
 
        String flupDoctorName = entity.getFlupDoctorName();
        if (flupDoctorName != null) {
            stmt.bindString(47, flupDoctorName);
        }
 
        String flupOrgCode = entity.getFlupOrgCode();
        if (flupOrgCode != null) {
            stmt.bindString(48, flupOrgCode);
        }
 
        String flupOrgName = entity.getFlupOrgName();
        if (flupOrgName != null) {
            stmt.bindString(49, flupOrgName);
        }
 
        String nextFlupDate = entity.getNextFlupDate();
        if (nextFlupDate != null) {
            stmt.bindString(50, nextFlupDate);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DiabetesFlup_down readEntity(Cursor cursor, int offset) {
        DiabetesFlup_down entity = new DiabetesFlup_down( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // businessKey
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // bmiTarget
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // personId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // healthFileNumber
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // bloodPressureLevel
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // flupDate
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // flupMode
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // symptomCodes
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // specialNo
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // symptomOther
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // SBP
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // DBP
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // weight
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // weightTarget
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // bmi
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // dorsalisPedisPulseCode
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // signsOther
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // dailySmoking
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // dailySmokingTarget
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // dailyDrinking
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // dailyDrinkingTarget
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // perWeekMovements
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // perWeekMovementsTarget
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // perWeekTimes
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // perWeekTimesTarget
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // stapleFood
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // stapleFoodTarget
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // psychologicalCode
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // complianceCode
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // fastingBloodGlucose
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // HbA1c
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // aidCheckDate
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // aidCheck
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // doseCode
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // adverseReactionCode
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // lowBloodSugarCode
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // flupTypeCode
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // medicationList
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // insulinMedicationType
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // insulinMedicationRate
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // insulinMedicationDose
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // referralReason
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // referralOrg
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // referralDepartment
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // flupDoctorCode
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // flupDoctorName
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // flupOrgCode
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // flupOrgName
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49) // nextFlupDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DiabetesFlup_down entity, int offset) {
        entity.setBusinessKey(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setBmiTarget(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPersonId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHealthFileNumber(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBloodPressureLevel(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFlupDate(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFlupMode(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSymptomCodes(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSpecialNo(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setSymptomOther(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setSBP(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setDBP(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setWeight(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setWeightTarget(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setBmi(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setDorsalisPedisPulseCode(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setSignsOther(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setDailySmoking(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setDailySmokingTarget(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setDailyDrinking(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setDailyDrinkingTarget(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setPerWeekMovements(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setPerWeekMovementsTarget(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setPerWeekTimes(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setPerWeekTimesTarget(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setStapleFood(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setStapleFoodTarget(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setPsychologicalCode(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setComplianceCode(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setFastingBloodGlucose(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setHbA1c(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setAidCheckDate(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setAidCheck(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setDoseCode(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setAdverseReactionCode(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setLowBloodSugarCode(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setFlupTypeCode(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setMedicationList(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setInsulinMedicationType(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setInsulinMedicationRate(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setInsulinMedicationDose(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setReferralReason(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setReferralOrg(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setReferralDepartment(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setFlupDoctorCode(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setFlupDoctorName(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setFlupOrgCode(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setFlupOrgName(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setNextFlupDate(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(DiabetesFlup_down entity, long rowId) {
        return entity.getBusinessKey();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(DiabetesFlup_down entity) {
        if(entity != null) {
            return entity.getBusinessKey();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
