package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HEALTH_RECORD__STATUS".
 */
public class HealthRecord_Status {

	private Long id;
	private String updateType;
	private String personId;
	private String machineNo;
	private String name;
	private String recordResultCode;
	private String recordResultDesc;

	// KEEP FIELDS - put your custom fields here

	public HealthRecord_Status() {
		updateType = "";
		personId = "";
		machineNo = "";
		name = "";
		recordResultCode = "";
		recordResultDesc = "";

	}

	// KEEP FIELDS END

	public HealthRecord_Status(Long id) {
		this.id = id;
	}

	public HealthRecord_Status(Long id, String updateType, String personId,
			String machineNo, String name, String recordResultCode,
			String recordResultDesc) {
		this.id = id;
		this.updateType = updateType;
		this.personId = personId;
		this.machineNo = machineNo;
		this.name = name;
		this.recordResultCode = recordResultCode;
		this.recordResultDesc = recordResultDesc;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUpdateType() {
		return updateType;
	}

	public void setUpdateType(String updateType) {
		this.updateType = updateType;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getMachineNo() {
		return machineNo;
	}

	public void setMachineNo(String machineNo) {
		this.machineNo = machineNo;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRecordResultCode() {
		return recordResultCode;
	}

	public void setRecordResultCode(String recordResultCode) {
		this.recordResultCode = recordResultCode;
	}

	public String getRecordResultDesc() {
		return recordResultDesc;
	}

	public void setRecordResultDesc(String recordResultDesc) {
		this.recordResultDesc = recordResultDesc;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
