package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HEALTH_EXAMINATION".
 */
public class HealthExamination {

	private String businessKey;
	private String personId;
	private String healthFileNumber;
	private String name;
	private String examinationDate;
	private String orgCode;
	private String operatorCode;
	private String operatorName;
	private String operateTime;
	private String responsibleDoctorCode;
	private String responsibleDoctorName;
	private String symptomCodes;
	private String symptomOther;
	private String temperature;
	private String pulseRate;
	private String respiratoryRate;
	private String height;
	private String weight;
	private String bmi;
	private String waistline;
	private String leftSBP;
	private String leftDBP;
	private String rightSBP;
	private String rightDBP;
	private String theAgedStatus;
	private String selfCareAbilityCode;
	private String cognitiveFunction;
	private String cognitiveFunctionScore;
	private String emotionalState;
	private String emotionalStateScore;
	private String exerciseFrequencyCode;
	private String everyWorkoutTime;
	private String insistOnExerciseTime;
	private String exerciseMode;
	private String eatingHabitsCodes;
	private String smokingStatusCode;
	private String dailySmoking;
	private String smokingAge;
	private String smokingCessationAge;
	private String drinkingFrequencyCode;
	private String dailyDrinking;
	private String temperanceCode;
	private String temperanceAge;
	private String drinkingAge;
	private String whetherDrunk;
	private String alcoholTypeCodes;
	private String alcoholTypeOther;
	private String exposureStateCode;
	private String hazardousWork;
	private String workingTime;
	private String dust;
	private String dustProtective;
	private String dustProtectiveDesc;
	private String radiogen;
	private String radiogenProtective;
	private String radiogenProtectiveDesc;
	private String physical;
	private String physicalProtective;
	private String physicalProtectiveDesc;
	private String chemistry;
	private String chemistryProtective;
	private String chemistryProtectiveDesc;
	private String otherToxicant;
	private String otherProtective;
	private String otherProtectiveDesc;
	private String lipsCode;
	private String dentitionCodes;
	private String missingTeethLeftUp;
	private String missingTeethRightUp;
	private String missingTeethLeftDown;
	private String missingTeethRightDown;
	private String cariesLeftUp;
	private String cariesRightUp;
	private String cariesLeftDown;
	private String cariesRightDown;
	private String dentureLeftUp;
	private String dentureRightUp;
	private String dentureLeftDown;
	private String dentureRightDown;
	private String throatCode;
	private String visionRight;
	private String visionLeft;
	private String redressVisionRight;
	private String redressVisionLeft;
	private String hearingCode;
	private String motorFunctionCode;
	private String fundusCode;
	private String fundusAbnormal;
	private String skinCode;
	private String skinOther;
	private String scleraCode;
	private String scleraOther;
	private String lymphNodeCode;
	private String lymphNodeOther;
	private String barrelChestCode;
	private String breathSoundCode;
	private String breathSoundOther;
	private String raleCode;
	private String raleOther;
	private String heartRate;
	private String rhythmCode;
	private String cardiacSouffleCode;
	private String cardiacSouffleDesc;
	private String abdomenTendernessCode;
	private String abdomenTendernessDesc;
	private String abdomenMassCode;
	private String abdomenMassDesc;
	private String abdomenLiverCode;
	private String abdomenLiverDesc;
	private String abdomenSplenomegalyCode;
	private String abdomenSplenomegalyDesc;
	private String abdomenShiftingDullnessCode;
	private String abdomenShiftingDullnessDesc;
	private String dorsalisPedisPulseCode;
	private String analFingerCodes;
	private String analFingerDesc;
	private String breastCodes;
	private String breastDesc;
	private String vulvaCode;
	private String vulvaDesc;
	private String vaginaCode;
	private String vaginaDesc;
	private String cervixCode;
	private String cervixDesc;
	private String uterusCode;
	private String uterusDesc;
	private String uterineAccessoriesCode;
	private String uterineAccessoriesDesc;
	private String examinationOther;
	private String hemoglobin;
	private String leucocyte;
	private String platelet;
	private String bloodOther;
	private String urineProteinCode;
	private String urineSugarCode;
	private String urineKetoneCode;
	private String urineOccultBloodCode;
	private String urineOther;
	private String fastingPlasmaGlucose1;
	private String fastingPlasmaGlucose2;
	private String ECGCode;
	private String ECGDesc;
	private String ECGData;
	private String urineTraceAlbuminCode;
	private String fecalOccultBloodCode;
	private String glycatedHemoglobin;
	private String HBsAgCode;
	private String GPT;
	private String GOT;
	private String albumin;
	private String TBIL;
	private String DBIL;
	private String serumCreatinine;
	private String BUN;
	private String serumPotassiumConcentration;
	private String serumSodiumConcentration;
	private String TCHO;
	private String triglyceride;
	private String LDL;
	private String HDL;
	private String chestXRayCode;
	private String chestXRayDesc;
	private String BScanCode;
	private String BScanDesc;
	private String papSmearCode;
	private String papSmearDesc;
	private String checkOther;
	private String flatAndQualityCode;
	private String qiDeficiencyCode;
	private String yangXuzhiCode;
	private String yinDeficiencyCode;
	private String phlegmDampnessQualityCode;
	private String hotAndHumidQualityCode;
	private String bloodStasisCode;
	private String qiStagnationCode;
	private String specialQualityCode;
	private String cerebrovascularCodes;
	private String cerebrovascularDesc;
	private String kidneyDiseaseCodes;
	private String kidneyDiseaseDesc;
	private String heartDiseaseCodes;
	private String heartDiseaseDesc;
	private String vascularDiseaseCodes;
	private String vascularDiseaseDesc;
	private String eyeDiseaseCodes;
	private String eyeDiseaseDesc;
	private String nerveSystemDiseaseCode;
	private String nerveSystemDiseaseDesc;
	private String otherSystemDiseaseCode;
	private String otherSystemDiseaseDesc;
	private String hospitalizedHistory;
	private String familyBedHistory;
	private String medicationList;
	private String vaccinationHistory;
	private String healthEvaluationCode;
	private String diseaseName1;
	private String diseaseName2;
	private String diseaseName3;
	private String diseaseName4;
	private String healthGuidanceCodes;
	private String healthGuidanceDesc;
	private String riskFactorsCodes;
	private String weightReduction;
	private String vaccinationName;
	private String riskFactorsOther;
	private String householdRegisterCode;
	private String machineExaminationNo;
	private String legEdemaCode;
	private String recordResultDesc;
	private String recordResultCode;
	private String machineNo;
	private String machineCode;

	// KEEP FIELDS - put your custom fields here

	public HealthExamination() {
		personId = "";
		healthFileNumber = "";
		name = "";
		examinationDate = "";
		orgCode = "";
		operatorCode = "";
		operatorName = "";
		operateTime = "";
		responsibleDoctorCode = "";
		responsibleDoctorName = "";
		symptomCodes = "";
		symptomOther = "";
		temperature = "";
		pulseRate = "";
		respiratoryRate = "";
		height = "";
		weight = "";
		bmi = "";
		waistline = "";
		leftSBP = "";
		leftDBP = "";
		rightSBP = "";
		rightDBP = "";
		theAgedStatus = "";
		selfCareAbilityCode = "";
		cognitiveFunction = "";
		cognitiveFunctionScore = "";
		emotionalState = "";
		emotionalStateScore = "";
		exerciseFrequencyCode = "";
		everyWorkoutTime = "";
		insistOnExerciseTime = "";
		exerciseMode = "";
		eatingHabitsCodes = "";
		smokingStatusCode = "";
		dailySmoking = "";
		smokingAge = "";
		smokingCessationAge = "";
		drinkingFrequencyCode = "";
		dailyDrinking = "";
		temperanceCode = "";
		temperanceAge = "";
		drinkingAge = "";
		whetherDrunk = "";
		alcoholTypeCodes = "";
		alcoholTypeOther = "";
		exposureStateCode = "";
		hazardousWork = "";
		workingTime = "";
		dust = "";
		dustProtective = "";
		dustProtectiveDesc = "";
		radiogen = "";
		radiogenProtective = "";
		radiogenProtectiveDesc = "";
		physical = "";
		physicalProtective = "";
		physicalProtectiveDesc = "";
		chemistry = "";
		chemistryProtective = "";
		chemistryProtectiveDesc = "";
		otherToxicant = "";
		otherProtective = "";
		otherProtectiveDesc = "";
		lipsCode = "";
		dentitionCodes = "";
		missingTeethLeftUp = "";
		missingTeethRightUp = "";
		missingTeethLeftDown = "";
		missingTeethRightDown = "";
		cariesLeftUp = "";
		cariesRightUp = "";
		cariesLeftDown = "";
		cariesRightDown = "";
		dentureLeftUp = "";
		dentureRightUp = "";
		dentureLeftDown = "";
		dentureRightDown = "";
		throatCode = "";
		visionRight = "";
		visionLeft = "";
		redressVisionRight = "";
		redressVisionLeft = "";
		hearingCode = "";
		motorFunctionCode = "";
		fundusCode = "";
		fundusAbnormal = "";
		skinCode = "";
		skinOther = "";
		scleraCode = "";
		scleraOther = "";
		lymphNodeCode = "";
		lymphNodeOther = "";
		barrelChestCode = "";
		breathSoundCode = "";
		breathSoundOther = "";
		raleCode = "";
		raleOther = "";
		heartRate = "";
		rhythmCode = "";
		cardiacSouffleCode = "";
		cardiacSouffleDesc = "";
		abdomenTendernessCode = "";
		abdomenTendernessDesc = "";
		abdomenMassCode = "";
		abdomenMassDesc = "";
		abdomenLiverCode = "";
		abdomenLiverDesc = "";
		abdomenSplenomegalyCode = "";
		abdomenSplenomegalyDesc = "";
		abdomenShiftingDullnessCode = "";
		abdomenShiftingDullnessDesc = "";
		dorsalisPedisPulseCode = "";
		analFingerCodes = "";
		analFingerDesc = "";
		breastCodes = "";
		breastDesc = "";
		vulvaCode = "";
		vulvaDesc = "";
		vaginaCode = "";
		vaginaDesc = "";
		cervixCode = "";
		cervixDesc = "";
		uterusCode = "";
		uterusDesc = "";
		uterineAccessoriesCode = "";
		uterineAccessoriesDesc = "";
		examinationOther = "";
		hemoglobin = "";
		leucocyte = "";
		platelet = "";
		bloodOther = "";
		urineProteinCode = "";
		urineSugarCode = "";
		urineKetoneCode = "";
		urineOccultBloodCode = "";
		urineOther = "";
		fastingPlasmaGlucose1 = "";
		fastingPlasmaGlucose2 = "";
		ECGCode = "";
		ECGDesc = "";
		ECGData = "";
		urineTraceAlbuminCode = "";
		fecalOccultBloodCode = "";
		glycatedHemoglobin = "";
		HBsAgCode = "";
		GPT = "";
		GOT = "";
		albumin = "";
		TBIL = "";
		DBIL = "";
		serumCreatinine = "";
		BUN = "";
		serumPotassiumConcentration = "";
		serumSodiumConcentration = "";
		TCHO = "";
		triglyceride = "";
		LDL = "";
		HDL = "";
		chestXRayCode = "";
		chestXRayDesc = "";
		BScanCode = "";
		BScanDesc = "";
		papSmearCode = "";
		papSmearDesc = "";
		checkOther = "";
		flatAndQualityCode = "";
		qiDeficiencyCode = "";
		yangXuzhiCode = "";
		yinDeficiencyCode = "";
		phlegmDampnessQualityCode = "";
		hotAndHumidQualityCode = "";
		bloodStasisCode = "";
		qiStagnationCode = "";
		specialQualityCode = "";
		cerebrovascularCodes = "";
		cerebrovascularDesc = "";
		kidneyDiseaseCodes = "";
		kidneyDiseaseDesc = "";
		heartDiseaseCodes = "";
		heartDiseaseDesc = "";
		vascularDiseaseCodes = "";
		vascularDiseaseDesc = "";
		eyeDiseaseCodes = "";
		eyeDiseaseDesc = "";
		nerveSystemDiseaseCode = "";
		nerveSystemDiseaseDesc = "";
		otherSystemDiseaseCode = "";
		otherSystemDiseaseDesc = "";
		hospitalizedHistory = "";
		familyBedHistory = "";
		medicationList = "";
		vaccinationHistory = "";
		healthEvaluationCode = "";
		diseaseName1 = "";
		diseaseName2 = "";
		diseaseName3 = "";
		diseaseName4 = "";
		healthGuidanceCodes = "";
		healthGuidanceDesc = "";
		riskFactorsCodes = "";
		weightReduction = "";
		vaccinationName = "";
		riskFactorsOther = "";
		householdRegisterCode = "";
		machineExaminationNo = "";
		legEdemaCode = "";
		recordResultDesc = "";
		recordResultCode = "";
		businessKey = "";
		machineNo = "";
		machineCode = "";
	}

	// KEEP FIELDS END

	public HealthExamination(String businessKey) {
		this.businessKey = businessKey;
	}

	public HealthExamination(String businessKey, String personId,
			String healthFileNumber, String name, String examinationDate,
			String orgCode, String operatorCode, String operatorName,
			String operateTime, String responsibleDoctorCode,
			String responsibleDoctorName, String symptomCodes,
			String symptomOther, String temperature, String pulseRate,
			String respiratoryRate, String height, String weight, String bmi,
			String waistline, String leftSBP, String leftDBP, String rightSBP,
			String rightDBP, String theAgedStatus, String selfCareAbilityCode,
			String cognitiveFunction, String cognitiveFunctionScore,
			String emotionalState, String emotionalStateScore,
			String exerciseFrequencyCode, String everyWorkoutTime,
			String insistOnExerciseTime, String exerciseMode,
			String eatingHabitsCodes, String smokingStatusCode,
			String dailySmoking, String smokingAge, String smokingCessationAge,
			String drinkingFrequencyCode, String dailyDrinking,
			String temperanceCode, String temperanceAge, String drinkingAge,
			String whetherDrunk, String alcoholTypeCodes,
			String alcoholTypeOther, String exposureStateCode,
			String hazardousWork, String workingTime, String dust,
			String dustProtective, String dustProtectiveDesc, String radiogen,
			String radiogenProtective, String radiogenProtectiveDesc,
			String physical, String physicalProtective,
			String physicalProtectiveDesc, String chemistry,
			String chemistryProtective, String chemistryProtectiveDesc,
			String otherToxicant, String otherProtective,
			String otherProtectiveDesc, String lipsCode, String dentitionCodes,
			String missingTeethLeftUp, String missingTeethRightUp,
			String missingTeethLeftDown, String missingTeethRightDown,
			String cariesLeftUp, String cariesRightUp, String cariesLeftDown,
			String cariesRightDown, String dentureLeftUp,
			String dentureRightUp, String dentureLeftDown,
			String dentureRightDown, String throatCode, String visionRight,
			String visionLeft, String redressVisionRight,
			String redressVisionLeft, String hearingCode,
			String motorFunctionCode, String fundusCode, String fundusAbnormal,
			String skinCode, String skinOther, String scleraCode,
			String scleraOther, String lymphNodeCode, String lymphNodeOther,
			String barrelChestCode, String breathSoundCode,
			String breathSoundOther, String raleCode, String raleOther,
			String heartRate, String rhythmCode, String cardiacSouffleCode,
			String cardiacSouffleDesc, String abdomenTendernessCode,
			String abdomenTendernessDesc, String abdomenMassCode,
			String abdomenMassDesc, String abdomenLiverCode,
			String abdomenLiverDesc, String abdomenSplenomegalyCode,
			String abdomenSplenomegalyDesc, String abdomenShiftingDullnessCode,
			String abdomenShiftingDullnessDesc, String dorsalisPedisPulseCode,
			String analFingerCodes, String analFingerDesc, String breastCodes,
			String breastDesc, String vulvaCode, String vulvaDesc,
			String vaginaCode, String vaginaDesc, String cervixCode,
			String cervixDesc, String uterusCode, String uterusDesc,
			String uterineAccessoriesCode, String uterineAccessoriesDesc,
			String examinationOther, String hemoglobin, String leucocyte,
			String platelet, String bloodOther, String urineProteinCode,
			String urineSugarCode, String urineKetoneCode,
			String urineOccultBloodCode, String urineOther,
			String fastingPlasmaGlucose1, String fastingPlasmaGlucose2,
			String ECGCode, String ECGDesc, String ECGData,
			String urineTraceAlbuminCode, String fecalOccultBloodCode,
			String glycatedHemoglobin, String HBsAgCode, String GPT,
			String GOT, String albumin, String TBIL, String DBIL,
			String serumCreatinine, String BUN,
			String serumPotassiumConcentration,
			String serumSodiumConcentration, String TCHO, String triglyceride,
			String LDL, String HDL, String chestXRayCode, String chestXRayDesc,
			String BScanCode, String BScanDesc, String papSmearCode,
			String papSmearDesc, String checkOther, String flatAndQualityCode,
			String qiDeficiencyCode, String yangXuzhiCode,
			String yinDeficiencyCode, String phlegmDampnessQualityCode,
			String hotAndHumidQualityCode, String bloodStasisCode,
			String qiStagnationCode, String specialQualityCode,
			String cerebrovascularCodes, String cerebrovascularDesc,
			String kidneyDiseaseCodes, String kidneyDiseaseDesc,
			String heartDiseaseCodes, String heartDiseaseDesc,
			String vascularDiseaseCodes, String vascularDiseaseDesc,
			String eyeDiseaseCodes, String eyeDiseaseDesc,
			String nerveSystemDiseaseCode, String nerveSystemDiseaseDesc,
			String otherSystemDiseaseCode, String otherSystemDiseaseDesc,
			String hospitalizedHistory, String familyBedHistory,
			String medicationList, String vaccinationHistory,
			String healthEvaluationCode, String diseaseName1,
			String diseaseName2, String diseaseName3, String diseaseName4,
			String healthGuidanceCodes, String healthGuidanceDesc,
			String riskFactorsCodes, String weightReduction,
			String vaccinationName, String riskFactorsOther,
			String householdRegisterCode, String machineExaminationNo,
			String legEdemaCode, String recordResultDesc,
			String recordResultCode, String machineNo, String machineCode) {
		this.businessKey = businessKey;
		this.personId = personId;
		this.healthFileNumber = healthFileNumber;
		this.name = name;
		this.examinationDate = examinationDate;
		this.orgCode = orgCode;
		this.operatorCode = operatorCode;
		this.operatorName = operatorName;
		this.operateTime = operateTime;
		this.responsibleDoctorCode = responsibleDoctorCode;
		this.responsibleDoctorName = responsibleDoctorName;
		this.symptomCodes = symptomCodes;
		this.symptomOther = symptomOther;
		this.temperature = temperature;
		this.pulseRate = pulseRate;
		this.respiratoryRate = respiratoryRate;
		this.height = height;
		this.weight = weight;
		this.bmi = bmi;
		this.waistline = waistline;
		this.leftSBP = leftSBP;
		this.leftDBP = leftDBP;
		this.rightSBP = rightSBP;
		this.rightDBP = rightDBP;
		this.theAgedStatus = theAgedStatus;
		this.selfCareAbilityCode = selfCareAbilityCode;
		this.cognitiveFunction = cognitiveFunction;
		this.cognitiveFunctionScore = cognitiveFunctionScore;
		this.emotionalState = emotionalState;
		this.emotionalStateScore = emotionalStateScore;
		this.exerciseFrequencyCode = exerciseFrequencyCode;
		this.everyWorkoutTime = everyWorkoutTime;
		this.insistOnExerciseTime = insistOnExerciseTime;
		this.exerciseMode = exerciseMode;
		this.eatingHabitsCodes = eatingHabitsCodes;
		this.smokingStatusCode = smokingStatusCode;
		this.dailySmoking = dailySmoking;
		this.smokingAge = smokingAge;
		this.smokingCessationAge = smokingCessationAge;
		this.drinkingFrequencyCode = drinkingFrequencyCode;
		this.dailyDrinking = dailyDrinking;
		this.temperanceCode = temperanceCode;
		this.temperanceAge = temperanceAge;
		this.drinkingAge = drinkingAge;
		this.whetherDrunk = whetherDrunk;
		this.alcoholTypeCodes = alcoholTypeCodes;
		this.alcoholTypeOther = alcoholTypeOther;
		this.exposureStateCode = exposureStateCode;
		this.hazardousWork = hazardousWork;
		this.workingTime = workingTime;
		this.dust = dust;
		this.dustProtective = dustProtective;
		this.dustProtectiveDesc = dustProtectiveDesc;
		this.radiogen = radiogen;
		this.radiogenProtective = radiogenProtective;
		this.radiogenProtectiveDesc = radiogenProtectiveDesc;
		this.physical = physical;
		this.physicalProtective = physicalProtective;
		this.physicalProtectiveDesc = physicalProtectiveDesc;
		this.chemistry = chemistry;
		this.chemistryProtective = chemistryProtective;
		this.chemistryProtectiveDesc = chemistryProtectiveDesc;
		this.otherToxicant = otherToxicant;
		this.otherProtective = otherProtective;
		this.otherProtectiveDesc = otherProtectiveDesc;
		this.lipsCode = lipsCode;
		this.dentitionCodes = dentitionCodes;
		this.missingTeethLeftUp = missingTeethLeftUp;
		this.missingTeethRightUp = missingTeethRightUp;
		this.missingTeethLeftDown = missingTeethLeftDown;
		this.missingTeethRightDown = missingTeethRightDown;
		this.cariesLeftUp = cariesLeftUp;
		this.cariesRightUp = cariesRightUp;
		this.cariesLeftDown = cariesLeftDown;
		this.cariesRightDown = cariesRightDown;
		this.dentureLeftUp = dentureLeftUp;
		this.dentureRightUp = dentureRightUp;
		this.dentureLeftDown = dentureLeftDown;
		this.dentureRightDown = dentureRightDown;
		this.throatCode = throatCode;
		this.visionRight = visionRight;
		this.visionLeft = visionLeft;
		this.redressVisionRight = redressVisionRight;
		this.redressVisionLeft = redressVisionLeft;
		this.hearingCode = hearingCode;
		this.motorFunctionCode = motorFunctionCode;
		this.fundusCode = fundusCode;
		this.fundusAbnormal = fundusAbnormal;
		this.skinCode = skinCode;
		this.skinOther = skinOther;
		this.scleraCode = scleraCode;
		this.scleraOther = scleraOther;
		this.lymphNodeCode = lymphNodeCode;
		this.lymphNodeOther = lymphNodeOther;
		this.barrelChestCode = barrelChestCode;
		this.breathSoundCode = breathSoundCode;
		this.breathSoundOther = breathSoundOther;
		this.raleCode = raleCode;
		this.raleOther = raleOther;
		this.heartRate = heartRate;
		this.rhythmCode = rhythmCode;
		this.cardiacSouffleCode = cardiacSouffleCode;
		this.cardiacSouffleDesc = cardiacSouffleDesc;
		this.abdomenTendernessCode = abdomenTendernessCode;
		this.abdomenTendernessDesc = abdomenTendernessDesc;
		this.abdomenMassCode = abdomenMassCode;
		this.abdomenMassDesc = abdomenMassDesc;
		this.abdomenLiverCode = abdomenLiverCode;
		this.abdomenLiverDesc = abdomenLiverDesc;
		this.abdomenSplenomegalyCode = abdomenSplenomegalyCode;
		this.abdomenSplenomegalyDesc = abdomenSplenomegalyDesc;
		this.abdomenShiftingDullnessCode = abdomenShiftingDullnessCode;
		this.abdomenShiftingDullnessDesc = abdomenShiftingDullnessDesc;
		this.dorsalisPedisPulseCode = dorsalisPedisPulseCode;
		this.analFingerCodes = analFingerCodes;
		this.analFingerDesc = analFingerDesc;
		this.breastCodes = breastCodes;
		this.breastDesc = breastDesc;
		this.vulvaCode = vulvaCode;
		this.vulvaDesc = vulvaDesc;
		this.vaginaCode = vaginaCode;
		this.vaginaDesc = vaginaDesc;
		this.cervixCode = cervixCode;
		this.cervixDesc = cervixDesc;
		this.uterusCode = uterusCode;
		this.uterusDesc = uterusDesc;
		this.uterineAccessoriesCode = uterineAccessoriesCode;
		this.uterineAccessoriesDesc = uterineAccessoriesDesc;
		this.examinationOther = examinationOther;
		this.hemoglobin = hemoglobin;
		this.leucocyte = leucocyte;
		this.platelet = platelet;
		this.bloodOther = bloodOther;
		this.urineProteinCode = urineProteinCode;
		this.urineSugarCode = urineSugarCode;
		this.urineKetoneCode = urineKetoneCode;
		this.urineOccultBloodCode = urineOccultBloodCode;
		this.urineOther = urineOther;
		this.fastingPlasmaGlucose1 = fastingPlasmaGlucose1;
		this.fastingPlasmaGlucose2 = fastingPlasmaGlucose2;
		this.ECGCode = ECGCode;
		this.ECGDesc = ECGDesc;
		this.ECGData = ECGData;
		this.urineTraceAlbuminCode = urineTraceAlbuminCode;
		this.fecalOccultBloodCode = fecalOccultBloodCode;
		this.glycatedHemoglobin = glycatedHemoglobin;
		this.HBsAgCode = HBsAgCode;
		this.GPT = GPT;
		this.GOT = GOT;
		this.albumin = albumin;
		this.TBIL = TBIL;
		this.DBIL = DBIL;
		this.serumCreatinine = serumCreatinine;
		this.BUN = BUN;
		this.serumPotassiumConcentration = serumPotassiumConcentration;
		this.serumSodiumConcentration = serumSodiumConcentration;
		this.TCHO = TCHO;
		this.triglyceride = triglyceride;
		this.LDL = LDL;
		this.HDL = HDL;
		this.chestXRayCode = chestXRayCode;
		this.chestXRayDesc = chestXRayDesc;
		this.BScanCode = BScanCode;
		this.BScanDesc = BScanDesc;
		this.papSmearCode = papSmearCode;
		this.papSmearDesc = papSmearDesc;
		this.checkOther = checkOther;
		this.flatAndQualityCode = flatAndQualityCode;
		this.qiDeficiencyCode = qiDeficiencyCode;
		this.yangXuzhiCode = yangXuzhiCode;
		this.yinDeficiencyCode = yinDeficiencyCode;
		this.phlegmDampnessQualityCode = phlegmDampnessQualityCode;
		this.hotAndHumidQualityCode = hotAndHumidQualityCode;
		this.bloodStasisCode = bloodStasisCode;
		this.qiStagnationCode = qiStagnationCode;
		this.specialQualityCode = specialQualityCode;
		this.cerebrovascularCodes = cerebrovascularCodes;
		this.cerebrovascularDesc = cerebrovascularDesc;
		this.kidneyDiseaseCodes = kidneyDiseaseCodes;
		this.kidneyDiseaseDesc = kidneyDiseaseDesc;
		this.heartDiseaseCodes = heartDiseaseCodes;
		this.heartDiseaseDesc = heartDiseaseDesc;
		this.vascularDiseaseCodes = vascularDiseaseCodes;
		this.vascularDiseaseDesc = vascularDiseaseDesc;
		this.eyeDiseaseCodes = eyeDiseaseCodes;
		this.eyeDiseaseDesc = eyeDiseaseDesc;
		this.nerveSystemDiseaseCode = nerveSystemDiseaseCode;
		this.nerveSystemDiseaseDesc = nerveSystemDiseaseDesc;
		this.otherSystemDiseaseCode = otherSystemDiseaseCode;
		this.otherSystemDiseaseDesc = otherSystemDiseaseDesc;
		this.hospitalizedHistory = hospitalizedHistory;
		this.familyBedHistory = familyBedHistory;
		this.medicationList = medicationList;
		this.vaccinationHistory = vaccinationHistory;
		this.healthEvaluationCode = healthEvaluationCode;
		this.diseaseName1 = diseaseName1;
		this.diseaseName2 = diseaseName2;
		this.diseaseName3 = diseaseName3;
		this.diseaseName4 = diseaseName4;
		this.healthGuidanceCodes = healthGuidanceCodes;
		this.healthGuidanceDesc = healthGuidanceDesc;
		this.riskFactorsCodes = riskFactorsCodes;
		this.weightReduction = weightReduction;
		this.vaccinationName = vaccinationName;
		this.riskFactorsOther = riskFactorsOther;
		this.householdRegisterCode = householdRegisterCode;
		this.machineExaminationNo = machineExaminationNo;
		this.legEdemaCode = legEdemaCode;
		this.recordResultDesc = recordResultDesc;
		this.recordResultCode = recordResultCode;
		this.machineNo = machineNo;
		this.machineCode = machineCode;
	}

	public String getBusinessKey() {
		return businessKey;
	}

	public void setBusinessKey(String businessKey) {
		this.businessKey = businessKey;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getHealthFileNumber() {
		return healthFileNumber;
	}

	public void setHealthFileNumber(String healthFileNumber) {
		this.healthFileNumber = healthFileNumber;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getExaminationDate() {
		return examinationDate;
	}

	public void setExaminationDate(String examinationDate) {
		this.examinationDate = examinationDate;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOperatorCode() {
		return operatorCode;
	}

	public void setOperatorCode(String operatorCode) {
		this.operatorCode = operatorCode;
	}

	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	public String getOperateTime() {
		return operateTime;
	}

	public void setOperateTime(String operateTime) {
		this.operateTime = operateTime;
	}

	public String getResponsibleDoctorCode() {
		return responsibleDoctorCode;
	}

	public void setResponsibleDoctorCode(String responsibleDoctorCode) {
		this.responsibleDoctorCode = responsibleDoctorCode;
	}

	public String getResponsibleDoctorName() {
		return responsibleDoctorName;
	}

	public void setResponsibleDoctorName(String responsibleDoctorName) {
		this.responsibleDoctorName = responsibleDoctorName;
	}

	public String getSymptomCodes() {
		return symptomCodes;
	}

	public void setSymptomCodes(String symptomCodes) {
		this.symptomCodes = symptomCodes;
	}

	public String getSymptomOther() {
		return symptomOther;
	}

	public void setSymptomOther(String symptomOther) {
		this.symptomOther = symptomOther;
	}

	public String getTemperature() {
		return temperature;
	}

	public void setTemperature(String temperature) {
		this.temperature = temperature;
	}

	public String getPulseRate() {
		return pulseRate;
	}

	public void setPulseRate(String pulseRate) {
		this.pulseRate = pulseRate;
	}

	public String getRespiratoryRate() {
		return respiratoryRate;
	}

	public void setRespiratoryRate(String respiratoryRate) {
		this.respiratoryRate = respiratoryRate;
	}

	public String getHeight() {
		return height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public String getWeight() {
		return weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getBmi() {
		return bmi;
	}

	public void setBmi(String bmi) {
		this.bmi = bmi;
	}

	public String getWaistline() {
		return waistline;
	}

	public void setWaistline(String waistline) {
		this.waistline = waistline;
	}

	public String getLeftSBP() {
		return leftSBP;
	}

	public void setLeftSBP(String leftSBP) {
		this.leftSBP = leftSBP;
	}

	public String getLeftDBP() {
		return leftDBP;
	}

	public void setLeftDBP(String leftDBP) {
		this.leftDBP = leftDBP;
	}

	public String getRightSBP() {
		return rightSBP;
	}

	public void setRightSBP(String rightSBP) {
		this.rightSBP = rightSBP;
	}

	public String getRightDBP() {
		return rightDBP;
	}

	public void setRightDBP(String rightDBP) {
		this.rightDBP = rightDBP;
	}

	public String getTheAgedStatus() {
		return theAgedStatus;
	}

	public void setTheAgedStatus(String theAgedStatus) {
		this.theAgedStatus = theAgedStatus;
	}

	public String getSelfCareAbilityCode() {
		return selfCareAbilityCode;
	}

	public void setSelfCareAbilityCode(String selfCareAbilityCode) {
		this.selfCareAbilityCode = selfCareAbilityCode;
	}

	public String getCognitiveFunction() {
		return cognitiveFunction;
	}

	public void setCognitiveFunction(String cognitiveFunction) {
		this.cognitiveFunction = cognitiveFunction;
	}

	public String getCognitiveFunctionScore() {
		return cognitiveFunctionScore;
	}

	public void setCognitiveFunctionScore(String cognitiveFunctionScore) {
		this.cognitiveFunctionScore = cognitiveFunctionScore;
	}

	public String getEmotionalState() {
		return emotionalState;
	}

	public void setEmotionalState(String emotionalState) {
		this.emotionalState = emotionalState;
	}

	public String getEmotionalStateScore() {
		return emotionalStateScore;
	}

	public void setEmotionalStateScore(String emotionalStateScore) {
		this.emotionalStateScore = emotionalStateScore;
	}

	public String getExerciseFrequencyCode() {
		return exerciseFrequencyCode;
	}

	public void setExerciseFrequencyCode(String exerciseFrequencyCode) {
		this.exerciseFrequencyCode = exerciseFrequencyCode;
	}

	public String getEveryWorkoutTime() {
		return everyWorkoutTime;
	}

	public void setEveryWorkoutTime(String everyWorkoutTime) {
		this.everyWorkoutTime = everyWorkoutTime;
	}

	public String getInsistOnExerciseTime() {
		return insistOnExerciseTime;
	}

	public void setInsistOnExerciseTime(String insistOnExerciseTime) {
		this.insistOnExerciseTime = insistOnExerciseTime;
	}

	public String getExerciseMode() {
		return exerciseMode;
	}

	public void setExerciseMode(String exerciseMode) {
		this.exerciseMode = exerciseMode;
	}

	public String getEatingHabitsCodes() {
		return eatingHabitsCodes;
	}

	public void setEatingHabitsCodes(String eatingHabitsCodes) {
		this.eatingHabitsCodes = eatingHabitsCodes;
	}

	public String getSmokingStatusCode() {
		return smokingStatusCode;
	}

	public void setSmokingStatusCode(String smokingStatusCode) {
		this.smokingStatusCode = smokingStatusCode;
	}

	public String getDailySmoking() {
		return dailySmoking;
	}

	public void setDailySmoking(String dailySmoking) {
		this.dailySmoking = dailySmoking;
	}

	public String getSmokingAge() {
		return smokingAge;
	}

	public void setSmokingAge(String smokingAge) {
		this.smokingAge = smokingAge;
	}

	public String getSmokingCessationAge() {
		return smokingCessationAge;
	}

	public void setSmokingCessationAge(String smokingCessationAge) {
		this.smokingCessationAge = smokingCessationAge;
	}

	public String getDrinkingFrequencyCode() {
		return drinkingFrequencyCode;
	}

	public void setDrinkingFrequencyCode(String drinkingFrequencyCode) {
		this.drinkingFrequencyCode = drinkingFrequencyCode;
	}

	public String getDailyDrinking() {
		return dailyDrinking;
	}

	public void setDailyDrinking(String dailyDrinking) {
		this.dailyDrinking = dailyDrinking;
	}

	public String getTemperanceCode() {
		return temperanceCode;
	}

	public void setTemperanceCode(String temperanceCode) {
		this.temperanceCode = temperanceCode;
	}

	public String getTemperanceAge() {
		return temperanceAge;
	}

	public void setTemperanceAge(String temperanceAge) {
		this.temperanceAge = temperanceAge;
	}

	public String getDrinkingAge() {
		return drinkingAge;
	}

	public void setDrinkingAge(String drinkingAge) {
		this.drinkingAge = drinkingAge;
	}

	public String getWhetherDrunk() {
		return whetherDrunk;
	}

	public void setWhetherDrunk(String whetherDrunk) {
		this.whetherDrunk = whetherDrunk;
	}

	public String getAlcoholTypeCodes() {
		return alcoholTypeCodes;
	}

	public void setAlcoholTypeCodes(String alcoholTypeCodes) {
		this.alcoholTypeCodes = alcoholTypeCodes;
	}

	public String getAlcoholTypeOther() {
		return alcoholTypeOther;
	}

	public void setAlcoholTypeOther(String alcoholTypeOther) {
		this.alcoholTypeOther = alcoholTypeOther;
	}

	public String getExposureStateCode() {
		return exposureStateCode;
	}

	public void setExposureStateCode(String exposureStateCode) {
		this.exposureStateCode = exposureStateCode;
	}

	public String getHazardousWork() {
		return hazardousWork;
	}

	public void setHazardousWork(String hazardousWork) {
		this.hazardousWork = hazardousWork;
	}

	public String getWorkingTime() {
		return workingTime;
	}

	public void setWorkingTime(String workingTime) {
		this.workingTime = workingTime;
	}

	public String getDust() {
		return dust;
	}

	public void setDust(String dust) {
		this.dust = dust;
	}

	public String getDustProtective() {
		return dustProtective;
	}

	public void setDustProtective(String dustProtective) {
		this.dustProtective = dustProtective;
	}

	public String getDustProtectiveDesc() {
		return dustProtectiveDesc;
	}

	public void setDustProtectiveDesc(String dustProtectiveDesc) {
		this.dustProtectiveDesc = dustProtectiveDesc;
	}

	public String getRadiogen() {
		return radiogen;
	}

	public void setRadiogen(String radiogen) {
		this.radiogen = radiogen;
	}

	public String getRadiogenProtective() {
		return radiogenProtective;
	}

	public void setRadiogenProtective(String radiogenProtective) {
		this.radiogenProtective = radiogenProtective;
	}

	public String getRadiogenProtectiveDesc() {
		return radiogenProtectiveDesc;
	}

	public void setRadiogenProtectiveDesc(String radiogenProtectiveDesc) {
		this.radiogenProtectiveDesc = radiogenProtectiveDesc;
	}

	public String getPhysical() {
		return physical;
	}

	public void setPhysical(String physical) {
		this.physical = physical;
	}

	public String getPhysicalProtective() {
		return physicalProtective;
	}

	public void setPhysicalProtective(String physicalProtective) {
		this.physicalProtective = physicalProtective;
	}

	public String getPhysicalProtectiveDesc() {
		return physicalProtectiveDesc;
	}

	public void setPhysicalProtectiveDesc(String physicalProtectiveDesc) {
		this.physicalProtectiveDesc = physicalProtectiveDesc;
	}

	public String getChemistry() {
		return chemistry;
	}

	public void setChemistry(String chemistry) {
		this.chemistry = chemistry;
	}

	public String getChemistryProtective() {
		return chemistryProtective;
	}

	public void setChemistryProtective(String chemistryProtective) {
		this.chemistryProtective = chemistryProtective;
	}

	public String getChemistryProtectiveDesc() {
		return chemistryProtectiveDesc;
	}

	public void setChemistryProtectiveDesc(String chemistryProtectiveDesc) {
		this.chemistryProtectiveDesc = chemistryProtectiveDesc;
	}

	public String getOtherToxicant() {
		return otherToxicant;
	}

	public void setOtherToxicant(String otherToxicant) {
		this.otherToxicant = otherToxicant;
	}

	public String getOtherProtective() {
		return otherProtective;
	}

	public void setOtherProtective(String otherProtective) {
		this.otherProtective = otherProtective;
	}

	public String getOtherProtectiveDesc() {
		return otherProtectiveDesc;
	}

	public void setOtherProtectiveDesc(String otherProtectiveDesc) {
		this.otherProtectiveDesc = otherProtectiveDesc;
	}

	public String getLipsCode() {
		return lipsCode;
	}

	public void setLipsCode(String lipsCode) {
		this.lipsCode = lipsCode;
	}

	public String getDentitionCodes() {
		return dentitionCodes;
	}

	public void setDentitionCodes(String dentitionCodes) {
		this.dentitionCodes = dentitionCodes;
	}

	public String getMissingTeethLeftUp() {
		return missingTeethLeftUp;
	}

	public void setMissingTeethLeftUp(String missingTeethLeftUp) {
		this.missingTeethLeftUp = missingTeethLeftUp;
	}

	public String getMissingTeethRightUp() {
		return missingTeethRightUp;
	}

	public void setMissingTeethRightUp(String missingTeethRightUp) {
		this.missingTeethRightUp = missingTeethRightUp;
	}

	public String getMissingTeethLeftDown() {
		return missingTeethLeftDown;
	}

	public void setMissingTeethLeftDown(String missingTeethLeftDown) {
		this.missingTeethLeftDown = missingTeethLeftDown;
	}

	public String getMissingTeethRightDown() {
		return missingTeethRightDown;
	}

	public void setMissingTeethRightDown(String missingTeethRightDown) {
		this.missingTeethRightDown = missingTeethRightDown;
	}

	public String getCariesLeftUp() {
		return cariesLeftUp;
	}

	public void setCariesLeftUp(String cariesLeftUp) {
		this.cariesLeftUp = cariesLeftUp;
	}

	public String getCariesRightUp() {
		return cariesRightUp;
	}

	public void setCariesRightUp(String cariesRightUp) {
		this.cariesRightUp = cariesRightUp;
	}

	public String getCariesLeftDown() {
		return cariesLeftDown;
	}

	public void setCariesLeftDown(String cariesLeftDown) {
		this.cariesLeftDown = cariesLeftDown;
	}

	public String getCariesRightDown() {
		return cariesRightDown;
	}

	public void setCariesRightDown(String cariesRightDown) {
		this.cariesRightDown = cariesRightDown;
	}

	public String getDentureLeftUp() {
		return dentureLeftUp;
	}

	public void setDentureLeftUp(String dentureLeftUp) {
		this.dentureLeftUp = dentureLeftUp;
	}

	public String getDentureRightUp() {
		return dentureRightUp;
	}

	public void setDentureRightUp(String dentureRightUp) {
		this.dentureRightUp = dentureRightUp;
	}

	public String getDentureLeftDown() {
		return dentureLeftDown;
	}

	public void setDentureLeftDown(String dentureLeftDown) {
		this.dentureLeftDown = dentureLeftDown;
	}

	public String getDentureRightDown() {
		return dentureRightDown;
	}

	public void setDentureRightDown(String dentureRightDown) {
		this.dentureRightDown = dentureRightDown;
	}

	public String getThroatCode() {
		return throatCode;
	}

	public void setThroatCode(String throatCode) {
		this.throatCode = throatCode;
	}

	public String getVisionRight() {
		return visionRight;
	}

	public void setVisionRight(String visionRight) {
		this.visionRight = visionRight;
	}

	public String getVisionLeft() {
		return visionLeft;
	}

	public void setVisionLeft(String visionLeft) {
		this.visionLeft = visionLeft;
	}

	public String getRedressVisionRight() {
		return redressVisionRight;
	}

	public void setRedressVisionRight(String redressVisionRight) {
		this.redressVisionRight = redressVisionRight;
	}

	public String getRedressVisionLeft() {
		return redressVisionLeft;
	}

	public void setRedressVisionLeft(String redressVisionLeft) {
		this.redressVisionLeft = redressVisionLeft;
	}

	public String getHearingCode() {
		return hearingCode;
	}

	public void setHearingCode(String hearingCode) {
		this.hearingCode = hearingCode;
	}

	public String getMotorFunctionCode() {
		return motorFunctionCode;
	}

	public void setMotorFunctionCode(String motorFunctionCode) {
		this.motorFunctionCode = motorFunctionCode;
	}

	public String getFundusCode() {
		return fundusCode;
	}

	public void setFundusCode(String fundusCode) {
		this.fundusCode = fundusCode;
	}

	public String getFundusAbnormal() {
		return fundusAbnormal;
	}

	public void setFundusAbnormal(String fundusAbnormal) {
		this.fundusAbnormal = fundusAbnormal;
	}

	public String getSkinCode() {
		return skinCode;
	}

	public void setSkinCode(String skinCode) {
		this.skinCode = skinCode;
	}

	public String getSkinOther() {
		return skinOther;
	}

	public void setSkinOther(String skinOther) {
		this.skinOther = skinOther;
	}

	public String getScleraCode() {
		return scleraCode;
	}

	public void setScleraCode(String scleraCode) {
		this.scleraCode = scleraCode;
	}

	public String getScleraOther() {
		return scleraOther;
	}

	public void setScleraOther(String scleraOther) {
		this.scleraOther = scleraOther;
	}

	public String getLymphNodeCode() {
		return lymphNodeCode;
	}

	public void setLymphNodeCode(String lymphNodeCode) {
		this.lymphNodeCode = lymphNodeCode;
	}

	public String getLymphNodeOther() {
		return lymphNodeOther;
	}

	public void setLymphNodeOther(String lymphNodeOther) {
		this.lymphNodeOther = lymphNodeOther;
	}

	public String getBarrelChestCode() {
		return barrelChestCode;
	}

	public void setBarrelChestCode(String barrelChestCode) {
		this.barrelChestCode = barrelChestCode;
	}

	public String getBreathSoundCode() {
		return breathSoundCode;
	}

	public void setBreathSoundCode(String breathSoundCode) {
		this.breathSoundCode = breathSoundCode;
	}

	public String getBreathSoundOther() {
		return breathSoundOther;
	}

	public void setBreathSoundOther(String breathSoundOther) {
		this.breathSoundOther = breathSoundOther;
	}

	public String getRaleCode() {
		return raleCode;
	}

	public void setRaleCode(String raleCode) {
		this.raleCode = raleCode;
	}

	public String getRaleOther() {
		return raleOther;
	}

	public void setRaleOther(String raleOther) {
		this.raleOther = raleOther;
	}

	public String getHeartRate() {
		return heartRate;
	}

	public void setHeartRate(String heartRate) {
		this.heartRate = heartRate;
	}

	public String getRhythmCode() {
		return rhythmCode;
	}

	public void setRhythmCode(String rhythmCode) {
		this.rhythmCode = rhythmCode;
	}

	public String getCardiacSouffleCode() {
		return cardiacSouffleCode;
	}

	public void setCardiacSouffleCode(String cardiacSouffleCode) {
		this.cardiacSouffleCode = cardiacSouffleCode;
	}

	public String getCardiacSouffleDesc() {
		return cardiacSouffleDesc;
	}

	public void setCardiacSouffleDesc(String cardiacSouffleDesc) {
		this.cardiacSouffleDesc = cardiacSouffleDesc;
	}

	public String getAbdomenTendernessCode() {
		return abdomenTendernessCode;
	}

	public void setAbdomenTendernessCode(String abdomenTendernessCode) {
		this.abdomenTendernessCode = abdomenTendernessCode;
	}

	public String getAbdomenTendernessDesc() {
		return abdomenTendernessDesc;
	}

	public void setAbdomenTendernessDesc(String abdomenTendernessDesc) {
		this.abdomenTendernessDesc = abdomenTendernessDesc;
	}

	public String getAbdomenMassCode() {
		return abdomenMassCode;
	}

	public void setAbdomenMassCode(String abdomenMassCode) {
		this.abdomenMassCode = abdomenMassCode;
	}

	public String getAbdomenMassDesc() {
		return abdomenMassDesc;
	}

	public void setAbdomenMassDesc(String abdomenMassDesc) {
		this.abdomenMassDesc = abdomenMassDesc;
	}

	public String getAbdomenLiverCode() {
		return abdomenLiverCode;
	}

	public void setAbdomenLiverCode(String abdomenLiverCode) {
		this.abdomenLiverCode = abdomenLiverCode;
	}

	public String getAbdomenLiverDesc() {
		return abdomenLiverDesc;
	}

	public void setAbdomenLiverDesc(String abdomenLiverDesc) {
		this.abdomenLiverDesc = abdomenLiverDesc;
	}

	public String getAbdomenSplenomegalyCode() {
		return abdomenSplenomegalyCode;
	}

	public void setAbdomenSplenomegalyCode(String abdomenSplenomegalyCode) {
		this.abdomenSplenomegalyCode = abdomenSplenomegalyCode;
	}

	public String getAbdomenSplenomegalyDesc() {
		return abdomenSplenomegalyDesc;
	}

	public void setAbdomenSplenomegalyDesc(String abdomenSplenomegalyDesc) {
		this.abdomenSplenomegalyDesc = abdomenSplenomegalyDesc;
	}

	public String getAbdomenShiftingDullnessCode() {
		return abdomenShiftingDullnessCode;
	}

	public void setAbdomenShiftingDullnessCode(
			String abdomenShiftingDullnessCode) {
		this.abdomenShiftingDullnessCode = abdomenShiftingDullnessCode;
	}

	public String getAbdomenShiftingDullnessDesc() {
		return abdomenShiftingDullnessDesc;
	}

	public void setAbdomenShiftingDullnessDesc(
			String abdomenShiftingDullnessDesc) {
		this.abdomenShiftingDullnessDesc = abdomenShiftingDullnessDesc;
	}

	public String getDorsalisPedisPulseCode() {
		return dorsalisPedisPulseCode;
	}

	public void setDorsalisPedisPulseCode(String dorsalisPedisPulseCode) {
		this.dorsalisPedisPulseCode = dorsalisPedisPulseCode;
	}

	public String getAnalFingerCodes() {
		return analFingerCodes;
	}

	public void setAnalFingerCodes(String analFingerCodes) {
		this.analFingerCodes = analFingerCodes;
	}

	public String getAnalFingerDesc() {
		return analFingerDesc;
	}

	public void setAnalFingerDesc(String analFingerDesc) {
		this.analFingerDesc = analFingerDesc;
	}

	public String getBreastCodes() {
		return breastCodes;
	}

	public void setBreastCodes(String breastCodes) {
		this.breastCodes = breastCodes;
	}

	public String getBreastDesc() {
		return breastDesc;
	}

	public void setBreastDesc(String breastDesc) {
		this.breastDesc = breastDesc;
	}

	public String getVulvaCode() {
		return vulvaCode;
	}

	public void setVulvaCode(String vulvaCode) {
		this.vulvaCode = vulvaCode;
	}

	public String getVulvaDesc() {
		return vulvaDesc;
	}

	public void setVulvaDesc(String vulvaDesc) {
		this.vulvaDesc = vulvaDesc;
	}

	public String getVaginaCode() {
		return vaginaCode;
	}

	public void setVaginaCode(String vaginaCode) {
		this.vaginaCode = vaginaCode;
	}

	public String getVaginaDesc() {
		return vaginaDesc;
	}

	public void setVaginaDesc(String vaginaDesc) {
		this.vaginaDesc = vaginaDesc;
	}

	public String getCervixCode() {
		return cervixCode;
	}

	public void setCervixCode(String cervixCode) {
		this.cervixCode = cervixCode;
	}

	public String getCervixDesc() {
		return cervixDesc;
	}

	public void setCervixDesc(String cervixDesc) {
		this.cervixDesc = cervixDesc;
	}

	public String getUterusCode() {
		return uterusCode;
	}

	public void setUterusCode(String uterusCode) {
		this.uterusCode = uterusCode;
	}

	public String getUterusDesc() {
		return uterusDesc;
	}

	public void setUterusDesc(String uterusDesc) {
		this.uterusDesc = uterusDesc;
	}

	public String getUterineAccessoriesCode() {
		return uterineAccessoriesCode;
	}

	public void setUterineAccessoriesCode(String uterineAccessoriesCode) {
		this.uterineAccessoriesCode = uterineAccessoriesCode;
	}

	public String getUterineAccessoriesDesc() {
		return uterineAccessoriesDesc;
	}

	public void setUterineAccessoriesDesc(String uterineAccessoriesDesc) {
		this.uterineAccessoriesDesc = uterineAccessoriesDesc;
	}

	public String getExaminationOther() {
		return examinationOther;
	}

	public void setExaminationOther(String examinationOther) {
		this.examinationOther = examinationOther;
	}

	public String getHemoglobin() {
		return hemoglobin;
	}

	public void setHemoglobin(String hemoglobin) {
		this.hemoglobin = hemoglobin;
	}

	public String getLeucocyte() {
		return leucocyte;
	}

	public void setLeucocyte(String leucocyte) {
		this.leucocyte = leucocyte;
	}

	public String getPlatelet() {
		return platelet;
	}

	public void setPlatelet(String platelet) {
		this.platelet = platelet;
	}

	public String getBloodOther() {
		return bloodOther;
	}

	public void setBloodOther(String bloodOther) {
		this.bloodOther = bloodOther;
	}

	public String getUrineProteinCode() {
		return urineProteinCode;
	}

	public void setUrineProteinCode(String urineProteinCode) {
		this.urineProteinCode = urineProteinCode;
	}

	public String getUrineSugarCode() {
		return urineSugarCode;
	}

	public void setUrineSugarCode(String urineSugarCode) {
		this.urineSugarCode = urineSugarCode;
	}

	public String getUrineKetoneCode() {
		return urineKetoneCode;
	}

	public void setUrineKetoneCode(String urineKetoneCode) {
		this.urineKetoneCode = urineKetoneCode;
	}

	public String getUrineOccultBloodCode() {
		return urineOccultBloodCode;
	}

	public void setUrineOccultBloodCode(String urineOccultBloodCode) {
		this.urineOccultBloodCode = urineOccultBloodCode;
	}

	public String getUrineOther() {
		return urineOther;
	}

	public void setUrineOther(String urineOther) {
		this.urineOther = urineOther;
	}

	public String getFastingPlasmaGlucose1() {
		return fastingPlasmaGlucose1;
	}

	public void setFastingPlasmaGlucose1(String fastingPlasmaGlucose1) {
		this.fastingPlasmaGlucose1 = fastingPlasmaGlucose1;
	}

	public String getFastingPlasmaGlucose2() {
		return fastingPlasmaGlucose2;
	}

	public void setFastingPlasmaGlucose2(String fastingPlasmaGlucose2) {
		this.fastingPlasmaGlucose2 = fastingPlasmaGlucose2;
	}

	public String getECGCode() {
		return ECGCode;
	}

	public void setECGCode(String ECGCode) {
		this.ECGCode = ECGCode;
	}

	public String getECGDesc() {
		return ECGDesc;
	}

	public void setECGDesc(String ECGDesc) {
		this.ECGDesc = ECGDesc;
	}

	public String getECGData() {
		return ECGData;
	}

	public void setECGData(String ECGData) {
		this.ECGData = ECGData;
	}

	public String getUrineTraceAlbuminCode() {
		return urineTraceAlbuminCode;
	}

	public void setUrineTraceAlbuminCode(String urineTraceAlbuminCode) {
		this.urineTraceAlbuminCode = urineTraceAlbuminCode;
	}

	public String getFecalOccultBloodCode() {
		return fecalOccultBloodCode;
	}

	public void setFecalOccultBloodCode(String fecalOccultBloodCode) {
		this.fecalOccultBloodCode = fecalOccultBloodCode;
	}

	public String getGlycatedHemoglobin() {
		return glycatedHemoglobin;
	}

	public void setGlycatedHemoglobin(String glycatedHemoglobin) {
		this.glycatedHemoglobin = glycatedHemoglobin;
	}

	public String getHBsAgCode() {
		return HBsAgCode;
	}

	public void setHBsAgCode(String HBsAgCode) {
		this.HBsAgCode = HBsAgCode;
	}

	public String getGPT() {
		return GPT;
	}

	public void setGPT(String GPT) {
		this.GPT = GPT;
	}

	public String getGOT() {
		return GOT;
	}

	public void setGOT(String GOT) {
		this.GOT = GOT;
	}

	public String getAlbumin() {
		return albumin;
	}

	public void setAlbumin(String albumin) {
		this.albumin = albumin;
	}

	public String getTBIL() {
		return TBIL;
	}

	public void setTBIL(String TBIL) {
		this.TBIL = TBIL;
	}

	public String getDBIL() {
		return DBIL;
	}

	public void setDBIL(String DBIL) {
		this.DBIL = DBIL;
	}

	public String getSerumCreatinine() {
		return serumCreatinine;
	}

	public void setSerumCreatinine(String serumCreatinine) {
		this.serumCreatinine = serumCreatinine;
	}

	public String getBUN() {
		return BUN;
	}

	public void setBUN(String BUN) {
		this.BUN = BUN;
	}

	public String getSerumPotassiumConcentration() {
		return serumPotassiumConcentration;
	}

	public void setSerumPotassiumConcentration(
			String serumPotassiumConcentration) {
		this.serumPotassiumConcentration = serumPotassiumConcentration;
	}

	public String getSerumSodiumConcentration() {
		return serumSodiumConcentration;
	}

	public void setSerumSodiumConcentration(String serumSodiumConcentration) {
		this.serumSodiumConcentration = serumSodiumConcentration;
	}

	public String getTCHO() {
		return TCHO;
	}

	public void setTCHO(String TCHO) {
		this.TCHO = TCHO;
	}

	public String getTriglyceride() {
		return triglyceride;
	}

	public void setTriglyceride(String triglyceride) {
		this.triglyceride = triglyceride;
	}

	public String getLDL() {
		return LDL;
	}

	public void setLDL(String LDL) {
		this.LDL = LDL;
	}

	public String getHDL() {
		return HDL;
	}

	public void setHDL(String HDL) {
		this.HDL = HDL;
	}

	public String getChestXRayCode() {
		return chestXRayCode;
	}

	public void setChestXRayCode(String chestXRayCode) {
		this.chestXRayCode = chestXRayCode;
	}

	public String getChestXRayDesc() {
		return chestXRayDesc;
	}

	public void setChestXRayDesc(String chestXRayDesc) {
		this.chestXRayDesc = chestXRayDesc;
	}

	public String getBScanCode() {
		return BScanCode;
	}

	public void setBScanCode(String BScanCode) {
		this.BScanCode = BScanCode;
	}

	public String getBScanDesc() {
		return BScanDesc;
	}

	public void setBScanDesc(String BScanDesc) {
		this.BScanDesc = BScanDesc;
	}

	public String getPapSmearCode() {
		return papSmearCode;
	}

	public void setPapSmearCode(String papSmearCode) {
		this.papSmearCode = papSmearCode;
	}

	public String getPapSmearDesc() {
		return papSmearDesc;
	}

	public void setPapSmearDesc(String papSmearDesc) {
		this.papSmearDesc = papSmearDesc;
	}

	public String getCheckOther() {
		return checkOther;
	}

	public void setCheckOther(String checkOther) {
		this.checkOther = checkOther;
	}

	public String getFlatAndQualityCode() {
		return flatAndQualityCode;
	}

	public void setFlatAndQualityCode(String flatAndQualityCode) {
		this.flatAndQualityCode = flatAndQualityCode;
	}

	public String getQiDeficiencyCode() {
		return qiDeficiencyCode;
	}

	public void setQiDeficiencyCode(String qiDeficiencyCode) {
		this.qiDeficiencyCode = qiDeficiencyCode;
	}

	public String getYangXuzhiCode() {
		return yangXuzhiCode;
	}

	public void setYangXuzhiCode(String yangXuzhiCode) {
		this.yangXuzhiCode = yangXuzhiCode;
	}

	public String getYinDeficiencyCode() {
		return yinDeficiencyCode;
	}

	public void setYinDeficiencyCode(String yinDeficiencyCode) {
		this.yinDeficiencyCode = yinDeficiencyCode;
	}

	public String getPhlegmDampnessQualityCode() {
		return phlegmDampnessQualityCode;
	}

	public void setPhlegmDampnessQualityCode(String phlegmDampnessQualityCode) {
		this.phlegmDampnessQualityCode = phlegmDampnessQualityCode;
	}

	public String getHotAndHumidQualityCode() {
		return hotAndHumidQualityCode;
	}

	public void setHotAndHumidQualityCode(String hotAndHumidQualityCode) {
		this.hotAndHumidQualityCode = hotAndHumidQualityCode;
	}

	public String getBloodStasisCode() {
		return bloodStasisCode;
	}

	public void setBloodStasisCode(String bloodStasisCode) {
		this.bloodStasisCode = bloodStasisCode;
	}

	public String getQiStagnationCode() {
		return qiStagnationCode;
	}

	public void setQiStagnationCode(String qiStagnationCode) {
		this.qiStagnationCode = qiStagnationCode;
	}

	public String getSpecialQualityCode() {
		return specialQualityCode;
	}

	public void setSpecialQualityCode(String specialQualityCode) {
		this.specialQualityCode = specialQualityCode;
	}

	public String getCerebrovascularCodes() {
		return cerebrovascularCodes;
	}

	public void setCerebrovascularCodes(String cerebrovascularCodes) {
		this.cerebrovascularCodes = cerebrovascularCodes;
	}

	public String getCerebrovascularDesc() {
		return cerebrovascularDesc;
	}

	public void setCerebrovascularDesc(String cerebrovascularDesc) {
		this.cerebrovascularDesc = cerebrovascularDesc;
	}

	public String getKidneyDiseaseCodes() {
		return kidneyDiseaseCodes;
	}

	public void setKidneyDiseaseCodes(String kidneyDiseaseCodes) {
		this.kidneyDiseaseCodes = kidneyDiseaseCodes;
	}

	public String getKidneyDiseaseDesc() {
		return kidneyDiseaseDesc;
	}

	public void setKidneyDiseaseDesc(String kidneyDiseaseDesc) {
		this.kidneyDiseaseDesc = kidneyDiseaseDesc;
	}

	public String getHeartDiseaseCodes() {
		return heartDiseaseCodes;
	}

	public void setHeartDiseaseCodes(String heartDiseaseCodes) {
		this.heartDiseaseCodes = heartDiseaseCodes;
	}

	public String getHeartDiseaseDesc() {
		return heartDiseaseDesc;
	}

	public void setHeartDiseaseDesc(String heartDiseaseDesc) {
		this.heartDiseaseDesc = heartDiseaseDesc;
	}

	public String getVascularDiseaseCodes() {
		return vascularDiseaseCodes;
	}

	public void setVascularDiseaseCodes(String vascularDiseaseCodes) {
		this.vascularDiseaseCodes = vascularDiseaseCodes;
	}

	public String getVascularDiseaseDesc() {
		return vascularDiseaseDesc;
	}

	public void setVascularDiseaseDesc(String vascularDiseaseDesc) {
		this.vascularDiseaseDesc = vascularDiseaseDesc;
	}

	public String getEyeDiseaseCodes() {
		return eyeDiseaseCodes;
	}

	public void setEyeDiseaseCodes(String eyeDiseaseCodes) {
		this.eyeDiseaseCodes = eyeDiseaseCodes;
	}

	public String getEyeDiseaseDesc() {
		return eyeDiseaseDesc;
	}

	public void setEyeDiseaseDesc(String eyeDiseaseDesc) {
		this.eyeDiseaseDesc = eyeDiseaseDesc;
	}

	public String getNerveSystemDiseaseCode() {
		return nerveSystemDiseaseCode;
	}

	public void setNerveSystemDiseaseCode(String nerveSystemDiseaseCode) {
		this.nerveSystemDiseaseCode = nerveSystemDiseaseCode;
	}

	public String getNerveSystemDiseaseDesc() {
		return nerveSystemDiseaseDesc;
	}

	public void setNerveSystemDiseaseDesc(String nerveSystemDiseaseDesc) {
		this.nerveSystemDiseaseDesc = nerveSystemDiseaseDesc;
	}

	public String getOtherSystemDiseaseCode() {
		return otherSystemDiseaseCode;
	}

	public void setOtherSystemDiseaseCode(String otherSystemDiseaseCode) {
		this.otherSystemDiseaseCode = otherSystemDiseaseCode;
	}

	public String getOtherSystemDiseaseDesc() {
		return otherSystemDiseaseDesc;
	}

	public void setOtherSystemDiseaseDesc(String otherSystemDiseaseDesc) {
		this.otherSystemDiseaseDesc = otherSystemDiseaseDesc;
	}

	public String getHospitalizedHistory() {
		return hospitalizedHistory;
	}

	public void setHospitalizedHistory(String hospitalizedHistory) {
		this.hospitalizedHistory = hospitalizedHistory;
	}

	public String getFamilyBedHistory() {
		return familyBedHistory;
	}

	public void setFamilyBedHistory(String familyBedHistory) {
		this.familyBedHistory = familyBedHistory;
	}

	public String getMedicationList() {
		return medicationList;
	}

	public void setMedicationList(String medicationList) {
		this.medicationList = medicationList;
	}

	public String getVaccinationHistory() {
		return vaccinationHistory;
	}

	public void setVaccinationHistory(String vaccinationHistory) {
		this.vaccinationHistory = vaccinationHistory;
	}

	public String getHealthEvaluationCode() {
		return healthEvaluationCode;
	}

	public void setHealthEvaluationCode(String healthEvaluationCode) {
		this.healthEvaluationCode = healthEvaluationCode;
	}

	public String getDiseaseName1() {
		return diseaseName1;
	}

	public void setDiseaseName1(String diseaseName1) {
		this.diseaseName1 = diseaseName1;
	}

	public String getDiseaseName2() {
		return diseaseName2;
	}

	public void setDiseaseName2(String diseaseName2) {
		this.diseaseName2 = diseaseName2;
	}

	public String getDiseaseName3() {
		return diseaseName3;
	}

	public void setDiseaseName3(String diseaseName3) {
		this.diseaseName3 = diseaseName3;
	}

	public String getDiseaseName4() {
		return diseaseName4;
	}

	public void setDiseaseName4(String diseaseName4) {
		this.diseaseName4 = diseaseName4;
	}

	public String getHealthGuidanceCodes() {
		return healthGuidanceCodes;
	}

	public void setHealthGuidanceCodes(String healthGuidanceCodes) {
		this.healthGuidanceCodes = healthGuidanceCodes;
	}

	public String getHealthGuidanceDesc() {
		return healthGuidanceDesc;
	}

	public void setHealthGuidanceDesc(String healthGuidanceDesc) {
		this.healthGuidanceDesc = healthGuidanceDesc;
	}

	public String getRiskFactorsCodes() {
		return riskFactorsCodes;
	}

	public void setRiskFactorsCodes(String riskFactorsCodes) {
		this.riskFactorsCodes = riskFactorsCodes;
	}

	public String getWeightReduction() {
		return weightReduction;
	}

	public void setWeightReduction(String weightReduction) {
		this.weightReduction = weightReduction;
	}

	public String getVaccinationName() {
		return vaccinationName;
	}

	public void setVaccinationName(String vaccinationName) {
		this.vaccinationName = vaccinationName;
	}

	public String getRiskFactorsOther() {
		return riskFactorsOther;
	}

	public void setRiskFactorsOther(String riskFactorsOther) {
		this.riskFactorsOther = riskFactorsOther;
	}

	public String getHouseholdRegisterCode() {
		return householdRegisterCode;
	}

	public void setHouseholdRegisterCode(String householdRegisterCode) {
		this.householdRegisterCode = householdRegisterCode;
	}

	public String getMachineExaminationNo() {
		return machineExaminationNo;
	}

	public void setMachineExaminationNo(String machineExaminationNo) {
		this.machineExaminationNo = machineExaminationNo;
	}

	public String getLegEdemaCode() {
		return legEdemaCode;
	}

	public void setLegEdemaCode(String legEdemaCode) {
		this.legEdemaCode = legEdemaCode;
	}

	public String getRecordResultDesc() {
		return recordResultDesc;
	}

	public void setRecordResultDesc(String recordResultDesc) {
		this.recordResultDesc = recordResultDesc;
	}

	public String getRecordResultCode() {
		return recordResultCode;
	}

	public void setRecordResultCode(String recordResultCode) {
		this.recordResultCode = recordResultCode;
	}

	public String getMachineNo() {
		return machineNo;
	}

	public void setMachineNo(String machineNo) {
		this.machineNo = machineNo;
	}

	public String getMachineCode() {
		return machineCode;
	}

	public void setMachineCode(String machineCode) {
		this.machineCode = machineCode;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
