package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HYPERTENSION_SPECIAL_DOWN".
 */
public class HypertensionSpecial_down {

	private String personId;
	private String specialNo;
	private String name;
	private String registerDate;
	private String registerOrgCode;
	private String registerDoctorCode;
	private String registerDoctorName;
	private String diagnoseDate;
	private String diagnoseOrgCode;
	private String diagnoseDoctorCode;
	private String diagnoseDoctorName;
	private String SBP;
	private String DBP;
	private String bloodPressureLevel;
	private String nextFlupDate;

	// KEEP FIELDS - put your custom fields here

	public HypertensionSpecial_down() {
		personId = "";
		specialNo = "";
		name = "";
		registerDate = "";
		registerOrgCode = "";
		registerDoctorCode = "";
		registerDoctorName = "";
		diagnoseDate = "";
		diagnoseOrgCode = "";
		diagnoseDoctorCode = "";
		diagnoseDoctorName = "";
		SBP = "";
		DBP = "";
		bloodPressureLevel = "";
		nextFlupDate = "";
	}

	// KEEP FIELDS END

	public HypertensionSpecial_down(String personId) {
		this.personId = personId;
	}

	public HypertensionSpecial_down(String personId, String specialNo,
			String name, String registerDate, String registerOrgCode,
			String registerDoctorCode, String registerDoctorName,
			String diagnoseDate, String diagnoseOrgCode,
			String diagnoseDoctorCode, String diagnoseDoctorName, String SBP,
			String DBP, String bloodPressureLevel, String nextFlupDate) {
		this.personId = personId;
		this.specialNo = specialNo;
		this.name = name;
		this.registerDate = registerDate;
		this.registerOrgCode = registerOrgCode;
		this.registerDoctorCode = registerDoctorCode;
		this.registerDoctorName = registerDoctorName;
		this.diagnoseDate = diagnoseDate;
		this.diagnoseOrgCode = diagnoseOrgCode;
		this.diagnoseDoctorCode = diagnoseDoctorCode;
		this.diagnoseDoctorName = diagnoseDoctorName;
		this.SBP = SBP;
		this.DBP = DBP;
		this.bloodPressureLevel = bloodPressureLevel;
		this.nextFlupDate = nextFlupDate;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getSpecialNo() {
		return specialNo;
	}

	public void setSpecialNo(String specialNo) {
		this.specialNo = specialNo;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRegisterDate() {
		return registerDate;
	}

	public void setRegisterDate(String registerDate) {
		this.registerDate = registerDate;
	}

	public String getRegisterOrgCode() {
		return registerOrgCode;
	}

	public void setRegisterOrgCode(String registerOrgCode) {
		this.registerOrgCode = registerOrgCode;
	}

	public String getRegisterDoctorCode() {
		return registerDoctorCode;
	}

	public void setRegisterDoctorCode(String registerDoctorCode) {
		this.registerDoctorCode = registerDoctorCode;
	}

	public String getRegisterDoctorName() {
		return registerDoctorName;
	}

	public void setRegisterDoctorName(String registerDoctorName) {
		this.registerDoctorName = registerDoctorName;
	}

	public String getDiagnoseDate() {
		return diagnoseDate;
	}

	public void setDiagnoseDate(String diagnoseDate) {
		this.diagnoseDate = diagnoseDate;
	}

	public String getDiagnoseOrgCode() {
		return diagnoseOrgCode;
	}

	public void setDiagnoseOrgCode(String diagnoseOrgCode) {
		this.diagnoseOrgCode = diagnoseOrgCode;
	}

	public String getDiagnoseDoctorCode() {
		return diagnoseDoctorCode;
	}

	public void setDiagnoseDoctorCode(String diagnoseDoctorCode) {
		this.diagnoseDoctorCode = diagnoseDoctorCode;
	}

	public String getDiagnoseDoctorName() {
		return diagnoseDoctorName;
	}

	public void setDiagnoseDoctorName(String diagnoseDoctorName) {
		this.diagnoseDoctorName = diagnoseDoctorName;
	}

	public String getSBP() {
		return SBP;
	}

	public void setSBP(String SBP) {
		this.SBP = SBP;
	}

	public String getDBP() {
		return DBP;
	}

	public void setDBP(String DBP) {
		this.DBP = DBP;
	}

	public String getBloodPressureLevel() {
		return bloodPressureLevel;
	}

	public void setBloodPressureLevel(String bloodPressureLevel) {
		this.bloodPressureLevel = bloodPressureLevel;
	}

	public String getNextFlupDate() {
		return nextFlupDate;
	}

	public void setNextFlupDate(String nextFlupDate) {
		this.nextFlupDate = nextFlupDate;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
