package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LOCAL_MEASUREMENT_NIAO_YE".
 */
public class LocalMeasurementNiaoYe {

	private Long id;
	private String personId;
	private String name;
	private String idCard;
	private String pro;
	private String bld;
	private String uglu;
	private String ket;
	private String nqt;
	private String time;

	// KEEP FIELDS - put your custom fields here

	public LocalMeasurementNiaoYe() {
		id = System.currentTimeMillis();
		personId = "";
		name = "";
		idCard = "";
		pro = "";
		bld = "";
		uglu = "";
		ket = "";
		nqt = "";
		time = "";
	}

	// KEEP FIELDS END

	public LocalMeasurementNiaoYe(Long id) {
		this.id = id;
	}

	public LocalMeasurementNiaoYe(Long id, String personId, String name,
			String idCard, String pro, String bld, String uglu, String ket,
			String nqt, String time) {
		this.id = id;
		this.personId = personId;
		this.name = name;
		this.idCard = idCard;
		this.pro = pro;
		this.bld = bld;
		this.uglu = uglu;
		this.ket = ket;
		this.nqt = nqt;
		this.time = time;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIdCard() {
		return idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getPro() {
		return pro;
	}

	public void setPro(String pro) {
		this.pro = pro;
	}

	public String getBld() {
		return bld;
	}

	public void setBld(String bld) {
		this.bld = bld;
	}

	public String getUglu() {
		return uglu;
	}

	public void setUglu(String uglu) {
		this.uglu = uglu;
	}

	public String getKet() {
		return ket;
	}

	public void setKet(String ket) {
		this.ket = ket;
	}

	public String getNqt() {
		return nqt;
	}

	public void setNqt(String nqt) {
		this.nqt = nqt;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
