package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LOCAL_MEASUREMENT_XUE_YA".
 */
public class LocalMeasurementXueYa {

	private Long id;
	private String personId;
	private String name;
	private String idCard;
//	private String responsibleDoctorCode;
	private String szy;
	private String ssy;
	private String ml;
	private String time;

	// KEEP FIELDS - put your custom fields here

	public LocalMeasurementXueYa() {
		id = System.currentTimeMillis();
		personId = "";
		name = "";
		idCard = "";
//		responsibleDoctorCode = "";
		szy = "";
		ssy = "";
		ml = "";
		time = "";
	}

	// KEEP FIELDS END

	public LocalMeasurementXueYa(Long id) {
		this.id = id;
	}

	public LocalMeasurementXueYa(Long id, String personId, String name,
			String idCard,String szy, String ssy, String ml, String time) {
		this.id = id;
		this.personId = personId;
		this.name = name;
		this.idCard = idCard;		
		this.szy = szy;
		this.ssy = ssy;
		this.ml = ml;
		this.time = time;
//		this.responsibleDoctorCode = responsibleDoctorCode;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIdCard() {
		return idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}
	
/*	public String getResponsibleDcotorCode() {
		return responsibleDoctorCode;
	}

	public void setResponsibleDoctorCode(String responsibleDoctorCode) {
		this.responsibleDoctorCode = responsibleDoctorCode;
	}
*/
	public String getSzy() {
		return szy;
	}

	public void setSzy(String szy) {
		this.szy = szy;
	}

	public String getSsy() {
		return ssy;
	}

	public void setSsy(String ssy) {
		this.ssy = ssy;
	}

	public String getMl() {
		return ml;
	}

	public void setMl(String ml) {
		this.ml = ml;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
