package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LOCAL_MEASUREMENT_XIN_DIAN".
 */
public class LocalMeasurementXinDian {

	private Long id;
	private String personId;
	private String name;
	private String idCard;
	private String xdsj;
	private String xdjg;
	private String time;

	// KEEP FIELDS - put your custom fields here

	public LocalMeasurementXinDian() {
		id = System.currentTimeMillis();
		personId = "";
		name = "";
		idCard = "";
		xdsj = "";
		xdjg = "";
		time = "";

	}

	// KEEP FIELDS END

	public LocalMeasurementXinDian(Long id) {
		this.id = id;
	}

	public LocalMeasurementXinDian(Long id, String personId, String name,
			String idCard, String xdsj, String xdjg, String time) {
		this.id = id;
		this.personId = personId;
		this.name = name;
		this.idCard = idCard;
		this.xdsj = xdsj;
		this.xdjg = xdjg;
		this.time = time;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIdCard() {
		return idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getXdsj() {
		return xdsj;
	}

	public void setXdsj(String xdsj) {
		this.xdsj = xdsj;
	}

	public String getXdjg() {
		return xdjg;
	}

	public void setXdjg(String xdjg) {
		this.xdjg = xdjg;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
