package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LOCAL_JIE_ZHEN".
 */
public class LocalJieZhen {

	private Long id;
	private String name;
	private String personId;
	private String gender;
	private String idCard;
	private String birthday;
	private String yibaokahao;
	private String jiezhen_doctor;
	private String date;
	private String bingren_des;
	private String xianbingshi;
	private String jiwangshi;
	private String yibanqingkuang;
	private String tigejiancha;
	private String xuetang;
	private String niaosuan;
	private String danguchun;
	private String niaoye;
	private String baixibao;
	private String xueya;
	private String tiwen;
	private String xindian;
	private String zhenduan;
	private String chuzhijihua;
	private String yongyaoqingkuang;
	private String yibanzhiliao;
	private String zhiliaojishu;
	private String qingchuangfenghe;
	private String mengzhenhuanyao;
	private String zhongyitizhibianshi;
	private String jiankangpingjia;
	private String jiankangzhidao;
	private String shoufeiguanli;
	private String tuifeiguanli;

	// KEEP FIELDS - put your custom fields here

	public LocalJieZhen() {
		id = System.currentTimeMillis();
		personId = "";
		name = "";
		gender = "";
		idCard = "";
		birthday = "";
		yibaokahao = "";
		jiezhen_doctor = "";
		date = "";
		bingren_des = "";
		xianbingshi = "";
		jiwangshi = "";
		yibanqingkuang = "";
		tigejiancha = "";
		xuetang = "";
		niaosuan = "";
		danguchun = "";
		niaoye = "";
		baixibao = "";
		xueya = "";
		tiwen = "";
		xindian = "";
		zhenduan = "";
		chuzhijihua = "";
		yongyaoqingkuang = "";
		yibanzhiliao = "";
		zhiliaojishu = "";
		qingchuangfenghe = "";
		mengzhenhuanyao = "";
		zhongyitizhibianshi = "";
		jiankangpingjia = "";
		jiankangzhidao = "";
		shoufeiguanli = "";
		tuifeiguanli = "";
	}

	// KEEP FIELDS END

	public LocalJieZhen(Long id) {
		this.id = id;
	}

	public LocalJieZhen(Long id, String name, String personId, String gender,
			String idCard, String birthday, String yibaokahao,
			String jiezhen_doctor, String date, String bingren_des,
			String xianbingshi, String jiwangshi, String yibanqingkuang,
			String tigejiancha, String xuetang, String niaosuan,
			String danguchun, String niaoye, String baixibao, String xueya,
			String tiwen, String xindian, String zhenduan, String chuzhijihua,
			String yongyaoqingkuang, String yibanzhiliao, String zhiliaojishu,
			String qingchuangfenghe, String mengzhenhuanyao,
			String zhongyitizhibianshi, String jiankangpingjia,
			String jiankangzhidao, String shoufeiguanli, String tuifeiguanli) {
		this.id = id;
		this.name = name;
		this.personId = personId;
		this.gender = gender;
		this.idCard = idCard;
		this.birthday = birthday;
		this.yibaokahao = yibaokahao;
		this.jiezhen_doctor = jiezhen_doctor;
		this.date = date;
		this.bingren_des = bingren_des;
		this.xianbingshi = xianbingshi;
		this.jiwangshi = jiwangshi;
		this.yibanqingkuang = yibanqingkuang;
		this.tigejiancha = tigejiancha;
		this.xuetang = xuetang;
		this.niaosuan = niaosuan;
		this.danguchun = danguchun;
		this.niaoye = niaoye;
		this.baixibao = baixibao;
		this.xueya = xueya;
		this.tiwen = tiwen;
		this.xindian = xindian;
		this.zhenduan = zhenduan;
		this.chuzhijihua = chuzhijihua;
		this.yongyaoqingkuang = yongyaoqingkuang;
		this.yibanzhiliao = yibanzhiliao;
		this.zhiliaojishu = zhiliaojishu;
		this.qingchuangfenghe = qingchuangfenghe;
		this.mengzhenhuanyao = mengzhenhuanyao;
		this.zhongyitizhibianshi = zhongyitizhibianshi;
		this.jiankangpingjia = jiankangpingjia;
		this.jiankangzhidao = jiankangzhidao;
		this.shoufeiguanli = shoufeiguanli;
		this.tuifeiguanli = tuifeiguanli;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getIdCard() {
		return idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getBirthday() {
		return birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getYibaokahao() {
		return yibaokahao;
	}

	public void setYibaokahao(String yibaokahao) {
		this.yibaokahao = yibaokahao;
	}

	public String getJiezhen_doctor() {
		return jiezhen_doctor;
	}

	public void setJiezhen_doctor(String jiezhen_doctor) {
		this.jiezhen_doctor = jiezhen_doctor;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getBingren_des() {
		return bingren_des;
	}

	public void setBingren_des(String bingren_des) {
		this.bingren_des = bingren_des;
	}

	public String getXianbingshi() {
		return xianbingshi;
	}

	public void setXianbingshi(String xianbingshi) {
		this.xianbingshi = xianbingshi;
	}

	public String getJiwangshi() {
		return jiwangshi;
	}

	public void setJiwangshi(String jiwangshi) {
		this.jiwangshi = jiwangshi;
	}

	public String getYibanqingkuang() {
		return yibanqingkuang;
	}

	public void setYibanqingkuang(String yibanqingkuang) {
		this.yibanqingkuang = yibanqingkuang;
	}

	public String getTigejiancha() {
		return tigejiancha;
	}

	public void setTigejiancha(String tigejiancha) {
		this.tigejiancha = tigejiancha;
	}

	public String getXuetang() {
		return xuetang;
	}

	public void setXuetang(String xuetang) {
		this.xuetang = xuetang;
	}

	public String getNiaosuan() {
		return niaosuan;
	}

	public void setNiaosuan(String niaosuan) {
		this.niaosuan = niaosuan;
	}

	public String getDanguchun() {
		return danguchun;
	}

	public void setDanguchun(String danguchun) {
		this.danguchun = danguchun;
	}

	public String getNiaoye() {
		return niaoye;
	}

	public void setNiaoye(String niaoye) {
		this.niaoye = niaoye;
	}

	public String getBaixibao() {
		return baixibao;
	}

	public void setBaixibao(String baixibao) {
		this.baixibao = baixibao;
	}

	public String getXueya() {
		return xueya;
	}

	public void setXueya(String xueya) {
		this.xueya = xueya;
	}

	public String getTiwen() {
		return tiwen;
	}

	public void setTiwen(String tiwen) {
		this.tiwen = tiwen;
	}

	public String getXindian() {
		return xindian;
	}

	public void setXindian(String xindian) {
		this.xindian = xindian;
	}

	public String getZhenduan() {
		return zhenduan;
	}

	public void setZhenduan(String zhenduan) {
		this.zhenduan = zhenduan;
	}

	public String getChuzhijihua() {
		return chuzhijihua;
	}

	public void setChuzhijihua(String chuzhijihua) {
		this.chuzhijihua = chuzhijihua;
	}

	public String getYongyaoqingkuang() {
		return yongyaoqingkuang;
	}

	public void setYongyaoqingkuang(String yongyaoqingkuang) {
		this.yongyaoqingkuang = yongyaoqingkuang;
	}

	public String getYibanzhiliao() {
		return yibanzhiliao;
	}

	public void setYibanzhiliao(String yibanzhiliao) {
		this.yibanzhiliao = yibanzhiliao;
	}

	public String getZhiliaojishu() {
		return zhiliaojishu;
	}

	public void setZhiliaojishu(String zhiliaojishu) {
		this.zhiliaojishu = zhiliaojishu;
	}

	public String getQingchuangfenghe() {
		return qingchuangfenghe;
	}

	public void setQingchuangfenghe(String qingchuangfenghe) {
		this.qingchuangfenghe = qingchuangfenghe;
	}

	public String getMengzhenhuanyao() {
		return mengzhenhuanyao;
	}

	public void setMengzhenhuanyao(String mengzhenhuanyao) {
		this.mengzhenhuanyao = mengzhenhuanyao;
	}

	public String getZhongyitizhibianshi() {
		return zhongyitizhibianshi;
	}

	public void setZhongyitizhibianshi(String zhongyitizhibianshi) {
		this.zhongyitizhibianshi = zhongyitizhibianshi;
	}

	public String getJiankangpingjia() {
		return jiankangpingjia;
	}

	public void setJiankangpingjia(String jiankangpingjia) {
		this.jiankangpingjia = jiankangpingjia;
	}

	public String getJiankangzhidao() {
		return jiankangzhidao;
	}

	public void setJiankangzhidao(String jiankangzhidao) {
		this.jiankangzhidao = jiankangzhidao;
	}

	public String getShoufeiguanli() {
		return shoufeiguanli;
	}

	public void setShoufeiguanli(String shoufeiguanli) {
		this.shoufeiguanli = shoufeiguanli;
	}

	public String getTuifeiguanli() {
		return tuifeiguanli;
	}

	public void setTuifeiguanli(String tuifeiguanli) {
		this.tuifeiguanli = tuifeiguanli;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
