package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LOCAL_ZHUAN_ZHEN".
 */
public class LocalZhuanZhen {

	private Long id;
	private String name;
	private String personId;
	private String gender;
	private String age;
	private String archive_code;
	private String telephone;
	private String address;
	private String in_company;
	private String out_company;
	private String date;
	private String jiezhen_keshi;
	private String in_doctor;
	private String out_doctor;
	private String doctor_telephone;
	private String first_image;
	private String zhenduan_result;
	private String jiancha_result;
	private String zhuyaobingshi;
	private String jiwangbingshi;
	private String zhiliaoguocheng;
	private String advice;

	// KEEP FIELDS - put your custom fields here

	public LocalZhuanZhen() {
		id = System.currentTimeMillis();
		personId="";
		name = "";
		gender = "";
		age = "";
		archive_code = "";
		telephone = "";
		address = "";
		in_company = "";
		out_company = "";
		date = "";
		jiezhen_keshi = "";
		in_doctor = "";
		out_doctor = "";
		doctor_telephone = "";
		first_image = "";
		zhenduan_result = "";
		jiancha_result = "";
		zhuyaobingshi = "";
		jiwangbingshi = "";
		zhiliaoguocheng = "";
		advice = "";

	}

	// KEEP FIELDS END

	public LocalZhuanZhen(Long id) {
		this.id = id;
	}

	public LocalZhuanZhen(Long id, String name, String personId, String gender,
			String age, String archive_code, String telephone, String address,
			String in_company, String out_company, String date,
			String jiezhen_keshi, String in_doctor, String out_doctor,
			String doctor_telephone, String first_image,
			String zhenduan_result, String jiancha_result,
			String zhuyaobingshi, String jiwangbingshi, String zhiliaoguocheng,
			String advice) {
		this.id = id;
		this.name = name;
		this.personId = personId;
		this.gender = gender;
		this.age = age;
		this.archive_code = archive_code;
		this.telephone = telephone;
		this.address = address;
		this.in_company = in_company;
		this.out_company = out_company;
		this.date = date;
		this.jiezhen_keshi = jiezhen_keshi;
		this.in_doctor = in_doctor;
		this.out_doctor = out_doctor;
		this.doctor_telephone = doctor_telephone;
		this.first_image = first_image;
		this.zhenduan_result = zhenduan_result;
		this.jiancha_result = jiancha_result;
		this.zhuyaobingshi = zhuyaobingshi;
		this.jiwangbingshi = jiwangbingshi;
		this.zhiliaoguocheng = zhiliaoguocheng;
		this.advice = advice;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getAge() {
		return age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getArchive_code() {
		return archive_code;
	}

	public void setArchive_code(String archive_code) {
		this.archive_code = archive_code;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getIn_company() {
		return in_company;
	}

	public void setIn_company(String in_company) {
		this.in_company = in_company;
	}

	public String getOut_company() {
		return out_company;
	}

	public void setOut_company(String out_company) {
		this.out_company = out_company;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getJiezhen_keshi() {
		return jiezhen_keshi;
	}

	public void setJiezhen_keshi(String jiezhen_keshi) {
		this.jiezhen_keshi = jiezhen_keshi;
	}

	public String getIn_doctor() {
		return in_doctor;
	}

	public void setIn_doctor(String in_doctor) {
		this.in_doctor = in_doctor;
	}

	public String getOut_doctor() {
		return out_doctor;
	}

	public void setOut_doctor(String out_doctor) {
		this.out_doctor = out_doctor;
	}

	public String getDoctor_telephone() {
		return doctor_telephone;
	}

	public void setDoctor_telephone(String doctor_telephone) {
		this.doctor_telephone = doctor_telephone;
	}

	public String getFirst_image() {
		return first_image;
	}

	public void setFirst_image(String first_image) {
		this.first_image = first_image;
	}

	public String getZhenduan_result() {
		return zhenduan_result;
	}

	public void setZhenduan_result(String zhenduan_result) {
		this.zhenduan_result = zhenduan_result;
	}

	public String getJiancha_result() {
		return jiancha_result;
	}

	public void setJiancha_result(String jiancha_result) {
		this.jiancha_result = jiancha_result;
	}

	public String getZhuyaobingshi() {
		return zhuyaobingshi;
	}

	public void setZhuyaobingshi(String zhuyaobingshi) {
		this.zhuyaobingshi = zhuyaobingshi;
	}

	public String getJiwangbingshi() {
		return jiwangbingshi;
	}

	public void setJiwangbingshi(String jiwangbingshi) {
		this.jiwangbingshi = jiwangbingshi;
	}

	public String getZhiliaoguocheng() {
		return zhiliaoguocheng;
	}

	public void setZhiliaoguocheng(String zhiliaoguocheng) {
		this.zhiliaoguocheng = zhiliaoguocheng;
	}

	public String getAdvice() {
		return advice;
	}

	public void setAdvice(String advice) {
		this.advice = advice;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
