package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ORG_DOWN".
 */
public class Org_down {

	private Long id;
	private String orgCode;
	private String orgName;
	private String orgType;
	private String parentOrgCode;
	private String areaCode;
	private String levelOrder;

	// KEEP FIELDS - put your custom fields here

	public Org_down() {
		orgCode = "";
		orgName = "";
		orgType = "";
		parentOrgCode = "";
		areaCode = "";
		levelOrder = "";

	}

	// KEEP FIELDS END

	public Org_down(Long id) {
		this.id = id;
	}

	public Org_down(Long id, String orgCode, String orgName, String orgType,
			String parentOrgCode, String areaCode, String levelOrder) {
		this.id = id;
		this.orgCode = orgCode;
		this.orgName = orgName;
		this.orgType = orgType;
		this.parentOrgCode = parentOrgCode;
		this.areaCode = areaCode;
		this.levelOrder = levelOrder;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getOrgType() {
		return orgType;
	}

	public void setOrgType(String orgType) {
		this.orgType = orgType;
	}

	public String getParentOrgCode() {
		return parentOrgCode;
	}

	public void setParentOrgCode(String parentOrgCode) {
		this.parentOrgCode = parentOrgCode;
	}

	public String getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getLevelOrder() {
		return levelOrder;
	}

	public void setLevelOrder(String levelOrder) {
		this.levelOrder = levelOrder;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
