package com.c102c.app.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PREGNANT_FIRST_CHECK_UPLOAD".
 */
public class PregnantFirstCheck_upload {

	private Long id;
	private String personId;
	private String specialNo;
	private String machineCode;
	private String machineNo;
	private String pregnantManualNo;
	private String name;
	private String antenatalCareDate;
	private String gestationalWeeks;
	private String age;
	private String husbandName;
	private String husbandAge;
	private String husbandPhone;
	private String gravidityTimes;
	private String deliveryTimes;
	private String vaginalDeliveryTimes;
	private String caesareanSectionTimes;
	private String LMP;
	private String expectedBirthDate;
	private String pastHistoryCodes;
	private String pastHistoryOther;
	private String familyHistoryCodes;
	private String familyHistoryOther;
	private String personalHistoryCodes;
	private String personalHistoryOther;
	private String surgeryHistoryCode;
	private String surgeryHistoryOther;
	private String abortionTimes;
	private String stillbirthTimes;
	private String deadBirthTimes;
	private String neonatalDeath;
	private String birthDefects;
	private String height;
	private String weight;
	private String bmi;
	private String SBP;
	private String DBP;
	private String cardiacAuscultationCode;
	private String cardiacAuscultationDesc;
	private String lungAuscultationCode;
	private String lungAuscultationDesc;
	private String vulvaCode;
	private String vulvaDesc;
	private String vaginaCode;
	private String vaginaDesc;
	private String cervixCode;
	private String cervixDesc;
	private String uterusCode;
	private String uterusDesc;
	private String uterineAccessoriesCode;
	private String uterineAccessoriesDesc;
	private String hemoglobin;
	private String leucocyte;
	private String platelet;
	private String bloodOther;
	private String urineProteinCode;
	private String urineSugarCode;
	private String urineKetoneCode;
	private String urineOccultBloodCode;
	private String urineOther;
	private String bloodGroupCode;
	private String rhBloodGroupCode;
	private String bloodGlucose;
	private String GPT;
	private String GOT;
	private String albumin;
	private String TBIL;
	private String DBIL;
	private String serumCreatinine;
	private String BUN;
	private String vaginalFluidCodes;
	private String vaginalFluidOther;
	private String vaginalCleanlinessCode;
	private String HBsAgCode;
	private String antiHBsCode;
	private String HBeAgCode;
	private String HBeAbCode;
	private String HBcAbCode;
	private String syphilisCode;
	private String HIVCode;
	private String BScan;
	private String overallAssessmentCode;
	private String overallAssessmentDesc;
	private String healthGuideCodes;
	private String healthGuideOther;
	private String referralCode;
	private String referralReason;
	private String referralOrg;
	private String referralDepartment;
	private String checkDoctorCode;
	private String checkDoctorName;
	private String checkOrgCode;
	private String checkOrgName;
	private String nextFlupDate;

	// KEEP FIELDS - put your custom fields here

	public PregnantFirstCheck_upload() {
		id = System.currentTimeMillis();
		personId = "";
		specialNo = "";
		machineCode = "";
		machineNo = "";
		pregnantManualNo = "";
		name = "";
		antenatalCareDate = "";
		gestationalWeeks = "";
		age = "";
		husbandName = "";
		husbandAge = "";
		husbandPhone = "";
		gravidityTimes = "";
		deliveryTimes = "";
		vaginalDeliveryTimes = "";
		caesareanSectionTimes = "";
		LMP = "";
		expectedBirthDate = "";
		pastHistoryCodes = "";
		pastHistoryOther = "";
		familyHistoryCodes = "";
		familyHistoryOther = "";
		personalHistoryCodes = "";
		personalHistoryOther = "";
		surgeryHistoryCode = "";
		surgeryHistoryOther = "";
		abortionTimes = "";
		stillbirthTimes = "";
		deadBirthTimes = "";
		neonatalDeath = "";
		birthDefects = "";
		height = "";
		weight = "";
		bmi = "";
		SBP = "";
		DBP = "";
		cardiacAuscultationCode = "";
		cardiacAuscultationDesc = "";
		lungAuscultationCode = "";
		lungAuscultationDesc = "";
		vulvaCode = "";
		vulvaDesc = "";
		vaginaCode = "";
		vaginaDesc = "";
		cervixCode = "";
		cervixDesc = "";
		uterusCode = "";
		uterusDesc = "";
		uterineAccessoriesCode = "";
		uterineAccessoriesDesc = "";
		hemoglobin = "";
		leucocyte = "";
		platelet = "";
		bloodOther = "";
		urineProteinCode = "";
		urineSugarCode = "";
		urineKetoneCode = "";
		urineOccultBloodCode = "";
		urineOther = "";
		bloodGroupCode = "";
		rhBloodGroupCode = "";
		bloodGlucose = "";
		GPT = "";
		GOT = "";
		albumin = "";
		TBIL = "";
		DBIL = "";
		serumCreatinine = "";
		BUN = "";
		vaginalFluidCodes = "";
		vaginalFluidOther = "";
		vaginalCleanlinessCode = "";
		HBsAgCode = "";
		antiHBsCode = "";
		HBeAgCode = "";
		HBeAbCode = "";
		HBcAbCode = "";
		syphilisCode = "";
		HIVCode = "";
		BScan = "";
		overallAssessmentCode = "";
		overallAssessmentDesc = "";
		healthGuideCodes = "";
		healthGuideOther = "";
		referralCode = "";
		referralReason = "";
		referralOrg = "";
		referralDepartment = "";
		checkDoctorCode = "";
		checkDoctorName = "";
		checkOrgCode = "";
		checkOrgName = "";
		nextFlupDate = "";

	}

	// KEEP FIELDS END

	public PregnantFirstCheck_upload(Long id) {
		this.id = id;
	}

	public PregnantFirstCheck_upload(Long id, String personId,
			String specialNo, String machineCode, String machineNo,
			String pregnantManualNo, String name, String antenatalCareDate,
			String gestationalWeeks, String age, String husbandName,
			String husbandAge, String husbandPhone, String gravidityTimes,
			String deliveryTimes, String vaginalDeliveryTimes,
			String caesareanSectionTimes, String LMP, String expectedBirthDate,
			String pastHistoryCodes, String pastHistoryOther,
			String familyHistoryCodes, String familyHistoryOther,
			String personalHistoryCodes, String personalHistoryOther,
			String surgeryHistoryCode, String surgeryHistoryOther,
			String abortionTimes, String stillbirthTimes,
			String deadBirthTimes, String neonatalDeath, String birthDefects,
			String height, String weight, String bmi, String SBP, String DBP,
			String cardiacAuscultationCode, String cardiacAuscultationDesc,
			String lungAuscultationCode, String lungAuscultationDesc,
			String vulvaCode, String vulvaDesc, String vaginaCode,
			String vaginaDesc, String cervixCode, String cervixDesc,
			String uterusCode, String uterusDesc,
			String uterineAccessoriesCode, String uterineAccessoriesDesc,
			String hemoglobin, String leucocyte, String platelet,
			String bloodOther, String urineProteinCode, String urineSugarCode,
			String urineKetoneCode, String urineOccultBloodCode,
			String urineOther, String bloodGroupCode, String rhBloodGroupCode,
			String bloodGlucose, String GPT, String GOT, String albumin,
			String TBIL, String DBIL, String serumCreatinine, String BUN,
			String vaginalFluidCodes, String vaginalFluidOther,
			String vaginalCleanlinessCode, String HBsAgCode,
			String antiHBsCode, String HBeAgCode, String HBeAbCode,
			String HBcAbCode, String syphilisCode, String HIVCode,
			String BScan, String overallAssessmentCode,
			String overallAssessmentDesc, String healthGuideCodes,
			String healthGuideOther, String referralCode,
			String referralReason, String referralOrg,
			String referralDepartment, String checkDoctorCode,
			String checkDoctorName, String checkOrgCode, String checkOrgName,
			String nextFlupDate) {
		this.id = id;
		this.personId = personId;
		this.specialNo = specialNo;
		this.machineCode = machineCode;
		this.machineNo = machineNo;
		this.pregnantManualNo = pregnantManualNo;
		this.name = name;
		this.antenatalCareDate = antenatalCareDate;
		this.gestationalWeeks = gestationalWeeks;
		this.age = age;
		this.husbandName = husbandName;
		this.husbandAge = husbandAge;
		this.husbandPhone = husbandPhone;
		this.gravidityTimes = gravidityTimes;
		this.deliveryTimes = deliveryTimes;
		this.vaginalDeliveryTimes = vaginalDeliveryTimes;
		this.caesareanSectionTimes = caesareanSectionTimes;
		this.LMP = LMP;
		this.expectedBirthDate = expectedBirthDate;
		this.pastHistoryCodes = pastHistoryCodes;
		this.pastHistoryOther = pastHistoryOther;
		this.familyHistoryCodes = familyHistoryCodes;
		this.familyHistoryOther = familyHistoryOther;
		this.personalHistoryCodes = personalHistoryCodes;
		this.personalHistoryOther = personalHistoryOther;
		this.surgeryHistoryCode = surgeryHistoryCode;
		this.surgeryHistoryOther = surgeryHistoryOther;
		this.abortionTimes = abortionTimes;
		this.stillbirthTimes = stillbirthTimes;
		this.deadBirthTimes = deadBirthTimes;
		this.neonatalDeath = neonatalDeath;
		this.birthDefects = birthDefects;
		this.height = height;
		this.weight = weight;
		this.bmi = bmi;
		this.SBP = SBP;
		this.DBP = DBP;
		this.cardiacAuscultationCode = cardiacAuscultationCode;
		this.cardiacAuscultationDesc = cardiacAuscultationDesc;
		this.lungAuscultationCode = lungAuscultationCode;
		this.lungAuscultationDesc = lungAuscultationDesc;
		this.vulvaCode = vulvaCode;
		this.vulvaDesc = vulvaDesc;
		this.vaginaCode = vaginaCode;
		this.vaginaDesc = vaginaDesc;
		this.cervixCode = cervixCode;
		this.cervixDesc = cervixDesc;
		this.uterusCode = uterusCode;
		this.uterusDesc = uterusDesc;
		this.uterineAccessoriesCode = uterineAccessoriesCode;
		this.uterineAccessoriesDesc = uterineAccessoriesDesc;
		this.hemoglobin = hemoglobin;
		this.leucocyte = leucocyte;
		this.platelet = platelet;
		this.bloodOther = bloodOther;
		this.urineProteinCode = urineProteinCode;
		this.urineSugarCode = urineSugarCode;
		this.urineKetoneCode = urineKetoneCode;
		this.urineOccultBloodCode = urineOccultBloodCode;
		this.urineOther = urineOther;
		this.bloodGroupCode = bloodGroupCode;
		this.rhBloodGroupCode = rhBloodGroupCode;
		this.bloodGlucose = bloodGlucose;
		this.GPT = GPT;
		this.GOT = GOT;
		this.albumin = albumin;
		this.TBIL = TBIL;
		this.DBIL = DBIL;
		this.serumCreatinine = serumCreatinine;
		this.BUN = BUN;
		this.vaginalFluidCodes = vaginalFluidCodes;
		this.vaginalFluidOther = vaginalFluidOther;
		this.vaginalCleanlinessCode = vaginalCleanlinessCode;
		this.HBsAgCode = HBsAgCode;
		this.antiHBsCode = antiHBsCode;
		this.HBeAgCode = HBeAgCode;
		this.HBeAbCode = HBeAbCode;
		this.HBcAbCode = HBcAbCode;
		this.syphilisCode = syphilisCode;
		this.HIVCode = HIVCode;
		this.BScan = BScan;
		this.overallAssessmentCode = overallAssessmentCode;
		this.overallAssessmentDesc = overallAssessmentDesc;
		this.healthGuideCodes = healthGuideCodes;
		this.healthGuideOther = healthGuideOther;
		this.referralCode = referralCode;
		this.referralReason = referralReason;
		this.referralOrg = referralOrg;
		this.referralDepartment = referralDepartment;
		this.checkDoctorCode = checkDoctorCode;
		this.checkDoctorName = checkDoctorName;
		this.checkOrgCode = checkOrgCode;
		this.checkOrgName = checkOrgName;
		this.nextFlupDate = nextFlupDate;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getSpecialNo() {
		return specialNo;
	}

	public void setSpecialNo(String specialNo) {
		this.specialNo = specialNo;
	}

	public String getMachineCode() {
		return machineCode;
	}

	public void setMachineCode(String machineCode) {
		this.machineCode = machineCode;
	}

	public String getMachineNo() {
		return machineNo;
	}

	public void setMachineNo(String machineNo) {
		this.machineNo = machineNo;
	}

	public String getPregnantManualNo() {
		return pregnantManualNo;
	}

	public void setPregnantManualNo(String pregnantManualNo) {
		this.pregnantManualNo = pregnantManualNo;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAntenatalCareDate() {
		return antenatalCareDate;
	}

	public void setAntenatalCareDate(String antenatalCareDate) {
		this.antenatalCareDate = antenatalCareDate;
	}

	public String getGestationalWeeks() {
		return gestationalWeeks;
	}

	public void setGestationalWeeks(String gestationalWeeks) {
		this.gestationalWeeks = gestationalWeeks;
	}

	public String getAge() {
		return age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getHusbandName() {
		return husbandName;
	}

	public void setHusbandName(String husbandName) {
		this.husbandName = husbandName;
	}

	public String getHusbandAge() {
		return husbandAge;
	}

	public void setHusbandAge(String husbandAge) {
		this.husbandAge = husbandAge;
	}

	public String getHusbandPhone() {
		return husbandPhone;
	}

	public void setHusbandPhone(String husbandPhone) {
		this.husbandPhone = husbandPhone;
	}

	public String getGravidityTimes() {
		return gravidityTimes;
	}

	public void setGravidityTimes(String gravidityTimes) {
		this.gravidityTimes = gravidityTimes;
	}

	public String getDeliveryTimes() {
		return deliveryTimes;
	}

	public void setDeliveryTimes(String deliveryTimes) {
		this.deliveryTimes = deliveryTimes;
	}

	public String getVaginalDeliveryTimes() {
		return vaginalDeliveryTimes;
	}

	public void setVaginalDeliveryTimes(String vaginalDeliveryTimes) {
		this.vaginalDeliveryTimes = vaginalDeliveryTimes;
	}

	public String getCaesareanSectionTimes() {
		return caesareanSectionTimes;
	}

	public void setCaesareanSectionTimes(String caesareanSectionTimes) {
		this.caesareanSectionTimes = caesareanSectionTimes;
	}

	public String getLMP() {
		return LMP;
	}

	public void setLMP(String LMP) {
		this.LMP = LMP;
	}

	public String getExpectedBirthDate() {
		return expectedBirthDate;
	}

	public void setExpectedBirthDate(String expectedBirthDate) {
		this.expectedBirthDate = expectedBirthDate;
	}

	public String getPastHistoryCodes() {
		return pastHistoryCodes;
	}

	public void setPastHistoryCodes(String pastHistoryCodes) {
		this.pastHistoryCodes = pastHistoryCodes;
	}

	public String getPastHistoryOther() {
		return pastHistoryOther;
	}

	public void setPastHistoryOther(String pastHistoryOther) {
		this.pastHistoryOther = pastHistoryOther;
	}

	public String getFamilyHistoryCodes() {
		return familyHistoryCodes;
	}

	public void setFamilyHistoryCodes(String familyHistoryCodes) {
		this.familyHistoryCodes = familyHistoryCodes;
	}

	public String getFamilyHistoryOther() {
		return familyHistoryOther;
	}

	public void setFamilyHistoryOther(String familyHistoryOther) {
		this.familyHistoryOther = familyHistoryOther;
	}

	public String getPersonalHistoryCodes() {
		return personalHistoryCodes;
	}

	public void setPersonalHistoryCodes(String personalHistoryCodes) {
		this.personalHistoryCodes = personalHistoryCodes;
	}

	public String getPersonalHistoryOther() {
		return personalHistoryOther;
	}

	public void setPersonalHistoryOther(String personalHistoryOther) {
		this.personalHistoryOther = personalHistoryOther;
	}

	public String getSurgeryHistoryCode() {
		return surgeryHistoryCode;
	}

	public void setSurgeryHistoryCode(String surgeryHistoryCode) {
		this.surgeryHistoryCode = surgeryHistoryCode;
	}

	public String getSurgeryHistoryOther() {
		return surgeryHistoryOther;
	}

	public void setSurgeryHistoryOther(String surgeryHistoryOther) {
		this.surgeryHistoryOther = surgeryHistoryOther;
	}

	public String getAbortionTimes() {
		return abortionTimes;
	}

	public void setAbortionTimes(String abortionTimes) {
		this.abortionTimes = abortionTimes;
	}

	public String getStillbirthTimes() {
		return stillbirthTimes;
	}

	public void setStillbirthTimes(String stillbirthTimes) {
		this.stillbirthTimes = stillbirthTimes;
	}

	public String getDeadBirthTimes() {
		return deadBirthTimes;
	}

	public void setDeadBirthTimes(String deadBirthTimes) {
		this.deadBirthTimes = deadBirthTimes;
	}

	public String getNeonatalDeath() {
		return neonatalDeath;
	}

	public void setNeonatalDeath(String neonatalDeath) {
		this.neonatalDeath = neonatalDeath;
	}

	public String getBirthDefects() {
		return birthDefects;
	}

	public void setBirthDefects(String birthDefects) {
		this.birthDefects = birthDefects;
	}

	public String getHeight() {
		return height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public String getWeight() {
		return weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getBmi() {
		return bmi;
	}

	public void setBmi(String bmi) {
		this.bmi = bmi;
	}

	public String getSBP() {
		return SBP;
	}

	public void setSBP(String SBP) {
		this.SBP = SBP;
	}

	public String getDBP() {
		return DBP;
	}

	public void setDBP(String DBP) {
		this.DBP = DBP;
	}

	public String getCardiacAuscultationCode() {
		return cardiacAuscultationCode;
	}

	public void setCardiacAuscultationCode(String cardiacAuscultationCode) {
		this.cardiacAuscultationCode = cardiacAuscultationCode;
	}

	public String getCardiacAuscultationDesc() {
		return cardiacAuscultationDesc;
	}

	public void setCardiacAuscultationDesc(String cardiacAuscultationDesc) {
		this.cardiacAuscultationDesc = cardiacAuscultationDesc;
	}

	public String getLungAuscultationCode() {
		return lungAuscultationCode;
	}

	public void setLungAuscultationCode(String lungAuscultationCode) {
		this.lungAuscultationCode = lungAuscultationCode;
	}

	public String getLungAuscultationDesc() {
		return lungAuscultationDesc;
	}

	public void setLungAuscultationDesc(String lungAuscultationDesc) {
		this.lungAuscultationDesc = lungAuscultationDesc;
	}

	public String getVulvaCode() {
		return vulvaCode;
	}

	public void setVulvaCode(String vulvaCode) {
		this.vulvaCode = vulvaCode;
	}

	public String getVulvaDesc() {
		return vulvaDesc;
	}

	public void setVulvaDesc(String vulvaDesc) {
		this.vulvaDesc = vulvaDesc;
	}

	public String getVaginaCode() {
		return vaginaCode;
	}

	public void setVaginaCode(String vaginaCode) {
		this.vaginaCode = vaginaCode;
	}

	public String getVaginaDesc() {
		return vaginaDesc;
	}

	public void setVaginaDesc(String vaginaDesc) {
		this.vaginaDesc = vaginaDesc;
	}

	public String getCervixCode() {
		return cervixCode;
	}

	public void setCervixCode(String cervixCode) {
		this.cervixCode = cervixCode;
	}

	public String getCervixDesc() {
		return cervixDesc;
	}

	public void setCervixDesc(String cervixDesc) {
		this.cervixDesc = cervixDesc;
	}

	public String getUterusCode() {
		return uterusCode;
	}

	public void setUterusCode(String uterusCode) {
		this.uterusCode = uterusCode;
	}

	public String getUterusDesc() {
		return uterusDesc;
	}

	public void setUterusDesc(String uterusDesc) {
		this.uterusDesc = uterusDesc;
	}

	public String getUterineAccessoriesCode() {
		return uterineAccessoriesCode;
	}

	public void setUterineAccessoriesCode(String uterineAccessoriesCode) {
		this.uterineAccessoriesCode = uterineAccessoriesCode;
	}

	public String getUterineAccessoriesDesc() {
		return uterineAccessoriesDesc;
	}

	public void setUterineAccessoriesDesc(String uterineAccessoriesDesc) {
		this.uterineAccessoriesDesc = uterineAccessoriesDesc;
	}

	public String getHemoglobin() {
		return hemoglobin;
	}

	public void setHemoglobin(String hemoglobin) {
		this.hemoglobin = hemoglobin;
	}

	public String getLeucocyte() {
		return leucocyte;
	}

	public void setLeucocyte(String leucocyte) {
		this.leucocyte = leucocyte;
	}

	public String getPlatelet() {
		return platelet;
	}

	public void setPlatelet(String platelet) {
		this.platelet = platelet;
	}

	public String getBloodOther() {
		return bloodOther;
	}

	public void setBloodOther(String bloodOther) {
		this.bloodOther = bloodOther;
	}

	public String getUrineProteinCode() {
		return urineProteinCode;
	}

	public void setUrineProteinCode(String urineProteinCode) {
		this.urineProteinCode = urineProteinCode;
	}

	public String getUrineSugarCode() {
		return urineSugarCode;
	}

	public void setUrineSugarCode(String urineSugarCode) {
		this.urineSugarCode = urineSugarCode;
	}

	public String getUrineKetoneCode() {
		return urineKetoneCode;
	}

	public void setUrineKetoneCode(String urineKetoneCode) {
		this.urineKetoneCode = urineKetoneCode;
	}

	public String getUrineOccultBloodCode() {
		return urineOccultBloodCode;
	}

	public void setUrineOccultBloodCode(String urineOccultBloodCode) {
		this.urineOccultBloodCode = urineOccultBloodCode;
	}

	public String getUrineOther() {
		return urineOther;
	}

	public void setUrineOther(String urineOther) {
		this.urineOther = urineOther;
	}

	public String getBloodGroupCode() {
		return bloodGroupCode;
	}

	public void setBloodGroupCode(String bloodGroupCode) {
		this.bloodGroupCode = bloodGroupCode;
	}

	public String getRhBloodGroupCode() {
		return rhBloodGroupCode;
	}

	public void setRhBloodGroupCode(String rhBloodGroupCode) {
		this.rhBloodGroupCode = rhBloodGroupCode;
	}

	public String getBloodGlucose() {
		return bloodGlucose;
	}

	public void setBloodGlucose(String bloodGlucose) {
		this.bloodGlucose = bloodGlucose;
	}

	public String getGPT() {
		return GPT;
	}

	public void setGPT(String GPT) {
		this.GPT = GPT;
	}

	public String getGOT() {
		return GOT;
	}

	public void setGOT(String GOT) {
		this.GOT = GOT;
	}

	public String getAlbumin() {
		return albumin;
	}

	public void setAlbumin(String albumin) {
		this.albumin = albumin;
	}

	public String getTBIL() {
		return TBIL;
	}

	public void setTBIL(String TBIL) {
		this.TBIL = TBIL;
	}

	public String getDBIL() {
		return DBIL;
	}

	public void setDBIL(String DBIL) {
		this.DBIL = DBIL;
	}

	public String getSerumCreatinine() {
		return serumCreatinine;
	}

	public void setSerumCreatinine(String serumCreatinine) {
		this.serumCreatinine = serumCreatinine;
	}

	public String getBUN() {
		return BUN;
	}

	public void setBUN(String BUN) {
		this.BUN = BUN;
	}

	public String getVaginalFluidCodes() {
		return vaginalFluidCodes;
	}

	public void setVaginalFluidCodes(String vaginalFluidCodes) {
		this.vaginalFluidCodes = vaginalFluidCodes;
	}

	public String getVaginalFluidOther() {
		return vaginalFluidOther;
	}

	public void setVaginalFluidOther(String vaginalFluidOther) {
		this.vaginalFluidOther = vaginalFluidOther;
	}

	public String getVaginalCleanlinessCode() {
		return vaginalCleanlinessCode;
	}

	public void setVaginalCleanlinessCode(String vaginalCleanlinessCode) {
		this.vaginalCleanlinessCode = vaginalCleanlinessCode;
	}

	public String getHBsAgCode() {
		return HBsAgCode;
	}

	public void setHBsAgCode(String HBsAgCode) {
		this.HBsAgCode = HBsAgCode;
	}

	public String getAntiHBsCode() {
		return antiHBsCode;
	}

	public void setAntiHBsCode(String antiHBsCode) {
		this.antiHBsCode = antiHBsCode;
	}

	public String getHBeAgCode() {
		return HBeAgCode;
	}

	public void setHBeAgCode(String HBeAgCode) {
		this.HBeAgCode = HBeAgCode;
	}

	public String getHBeAbCode() {
		return HBeAbCode;
	}

	public void setHBeAbCode(String HBeAbCode) {
		this.HBeAbCode = HBeAbCode;
	}

	public String getHBcAbCode() {
		return HBcAbCode;
	}

	public void setHBcAbCode(String HBcAbCode) {
		this.HBcAbCode = HBcAbCode;
	}

	public String getSyphilisCode() {
		return syphilisCode;
	}

	public void setSyphilisCode(String syphilisCode) {
		this.syphilisCode = syphilisCode;
	}

	public String getHIVCode() {
		return HIVCode;
	}

	public void setHIVCode(String HIVCode) {
		this.HIVCode = HIVCode;
	}

	public String getBScan() {
		return BScan;
	}

	public void setBScan(String BScan) {
		this.BScan = BScan;
	}

	public String getOverallAssessmentCode() {
		return overallAssessmentCode;
	}

	public void setOverallAssessmentCode(String overallAssessmentCode) {
		this.overallAssessmentCode = overallAssessmentCode;
	}

	public String getOverallAssessmentDesc() {
		return overallAssessmentDesc;
	}

	public void setOverallAssessmentDesc(String overallAssessmentDesc) {
		this.overallAssessmentDesc = overallAssessmentDesc;
	}

	public String getHealthGuideCodes() {
		return healthGuideCodes;
	}

	public void setHealthGuideCodes(String healthGuideCodes) {
		this.healthGuideCodes = healthGuideCodes;
	}

	public String getHealthGuideOther() {
		return healthGuideOther;
	}

	public void setHealthGuideOther(String healthGuideOther) {
		this.healthGuideOther = healthGuideOther;
	}

	public String getReferralCode() {
		return referralCode;
	}

	public void setReferralCode(String referralCode) {
		this.referralCode = referralCode;
	}

	public String getReferralReason() {
		return referralReason;
	}

	public void setReferralReason(String referralReason) {
		this.referralReason = referralReason;
	}

	public String getReferralOrg() {
		return referralOrg;
	}

	public void setReferralOrg(String referralOrg) {
		this.referralOrg = referralOrg;
	}

	public String getReferralDepartment() {
		return referralDepartment;
	}

	public void setReferralDepartment(String referralDepartment) {
		this.referralDepartment = referralDepartment;
	}

	public String getCheckDoctorCode() {
		return checkDoctorCode;
	}

	public void setCheckDoctorCode(String checkDoctorCode) {
		this.checkDoctorCode = checkDoctorCode;
	}

	public String getCheckDoctorName() {
		return checkDoctorName;
	}

	public void setCheckDoctorName(String checkDoctorName) {
		this.checkDoctorName = checkDoctorName;
	}

	public String getCheckOrgCode() {
		return checkOrgCode;
	}

	public void setCheckOrgCode(String checkOrgCode) {
		this.checkOrgCode = checkOrgCode;
	}

	public String getCheckOrgName() {
		return checkOrgName;
	}

	public void setCheckOrgName(String checkOrgName) {
		this.checkOrgName = checkOrgName;
	}

	public String getNextFlupDate() {
		return nextFlupDate;
	}

	public void setNextFlupDate(String nextFlupDate) {
		this.nextFlupDate = nextFlupDate;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
